BEGIN TRANSACTION;
CREATE TABLE `ai_agent_configs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`userId` integer NOT NULL,
	`name` text NOT NULL,
	`agentType` text NOT NULL,
	`description` text,
	`capabilities` text DEFAULT '{"readEmails":false,"sendEmails":false,"manageCalendar":false,"createTasks":true,"manageInvoices":false,"fileAccess":false,"clientCommunication":true}',
	`webhookUrl` text,
	`webhookSecret` text,
	`model` text DEFAULT 'gpt-4',
	`temperature` real DEFAULT 0.7,
	`systemPrompt` text,
	`autoRun` integer DEFAULT false NOT NULL,
	`runSchedule` text,
	`lastRunAt` integer,
	`isActive` integer DEFAULT true NOT NULL,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `ai_agent_runs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`agentId` integer NOT NULL,
	`userId` integer NOT NULL,
	`triggerType` text NOT NULL,
	`status` text DEFAULT 'running' NOT NULL,
	`input` text,
	`output` text,
	`actionsTaken` text,
	`errorMessage` text,
	`durationMs` integer,
	`startedAt` integer,
	`completedAt` integer
);
CREATE TABLE `calendar_events` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`userId` integer NOT NULL,
	`clientId` integer,
	`connectedAccountId` integer,
	`taskId` integer,
	`googleEventId` text,
	`outlookEventId` text,
	`title` text NOT NULL,
	`description` text,
	`location` text,
	`startDate` integer NOT NULL,
	`endDate` integer NOT NULL,
	`isAllDay` integer DEFAULT false NOT NULL,
	`attendees` text,
	`recurrence` text,
	`color` text,
	`isRecurring` integer DEFAULT false NOT NULL,
	`status` text DEFAULT 'confirmed' NOT NULL,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `client_dashboard_snapshots` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`userId` integer NOT NULL,
	`revenue` real DEFAULT 0,
	`expenses` real DEFAULT 0,
	`netIncome` real DEFAULT 0,
	`assets` real DEFAULT 0,
	`liabilities` real DEFAULT 0,
	`equity` real DEFAULT 0,
	`periodStart` integer,
	`periodEnd` integer,
	`source` text DEFAULT 'manual',
	`createdAt` integer
);
CREATE TABLE `client_emails` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`email` text NOT NULL,
	`label` text DEFAULT 'general' NOT NULL,
	`isDefault` integer DEFAULT false NOT NULL,
	`notes` text,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `client_gov_reps` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`craRepName` text,
	`craRepNumber` text,
	`craRepPhone` text,
	`craRepEmail` text,
	`craAuthorizationLevel` text DEFAULT 'level_1',
	`craAuthorizationStart` integer,
	`craAuthorizationEnd` integer,
	`irsRepName` text,
	`irsRepPtin` text,
	`irsRepPhone` text,
	`irsRepEmail` text,
	`irsRepType` text,
	`irsForm2848Date` integer,
	`irsForm8821Date` integer,
	`stateTaxRepName` text,
	`stateTaxRepPhone` text,
	`stateTaxRepEmail` text,
	`notes` text,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `client_onboarding` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`token` text NOT NULL,
	`businessLegalName` text,
	`businessOperatingName` text,
	`businessStructure` text,
	`industry` text,
	`incorporationDate` integer,
	`businessNumber` text,
	`ein` text,
	`craBusinessNumber` text,
	`hstGstNumber` text,
	`payrollAccountNumber` text,
	`wsibAccountNumber` text,
	`primaryContactName` text,
	`primaryContactEmail` text,
	`primaryContactPhone` text,
	`secondaryContactName` text,
	`secondaryContactEmail` text,
	`bankName` text,
	`bankAccountNumber` text,
	`bankRoutingNumber` text,
	`currentAccountingSoftware` text,
	`currentPayrollProvider` text,
	`servicesNeeded` text,
	`painPoints` text,
	`expectations` text,
	`fiscalYearEnd` text,
	`lastFiledYear` text,
	`outstandingFilings` text,
	`hstGstFrequency` text DEFAULT 'none',
	`payrollFrequency` text DEFAULT 'none',
	`hasEmployees` integer DEFAULT false,
	`hasSubcontractors` integer DEFAULT false,
	`hasInvestments` integer DEFAULT false,
	`wsibRequired` integer DEFAULT false,
	`bankAccountCount` integer DEFAULT 1,
	`creditCardCount` integer DEFAULT 0,
	`needsYearEnd` integer DEFAULT true,
	`usesStripe` integer DEFAULT false,
	`usesSquare` integer DEFAULT false,
	`usesJobber` integer DEFAULT false,
	`salesEntryFrequency` text DEFAULT 'monthly',
	`status` text DEFAULT 'pending' NOT NULL,
	`submittedAt` integer,
	`reviewedBy` integer,
	`reviewedAt` integer,
	`notes` text,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `client_playbooks` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`userId` integer NOT NULL,
	`autoGenerated` integer DEFAULT false NOT NULL,
	`sections` text,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `client_task_rules` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`userId` integer NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`category` text,
	`priority` text DEFAULT 'medium' NOT NULL,
	`assignedTo` text,
	`ruleType` text NOT NULL,
	`frequency` text NOT NULL,
	`dueDayOfMonth` integer DEFAULT 15,
	`dueMonth` integer,
	`daysBeforeDue` integer DEFAULT 0,
	`fiscalYearEndMonth` integer,
	`fiscalYearEndDay` integer DEFAULT 31,
	`active` integer DEFAULT true NOT NULL,
	`nextDueDate` integer NOT NULL,
	`lastGeneratedDate` integer,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `client_vault` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`bankName` text,
	`bankAccountNumber` text,
	`bankRoutingNumber` text,
	`bankTransitNumber` text,
	`bankBranch` text,
	`bankLogin` text,
	`bankPassword` text,
	`creditCardNumber` text,
	`creditCardExpiry` text,
	`creditCardCvv` text,
	`qboLogin` text,
	`qboPassword` text,
	`xeroLogin` text,
	`xeroPassword` text,
	`waveLogin` text,
	`wavePassword` text,
	`freshbooksLogin` text,
	`freshbooksPassword` text,
	`otherSoftwareLogins` text,
	`craMyAccountLogin` text,
	`craMyAccountPassword` text,
	`craRepId` text,
	`craAuthorizationDate` integer,
	`irsLogin` text,
	`irsPassword` text,
	`irsCafNumber` text,
	`irsPowerOfAttorneyDate` integer,
	`vaultNotes` text,
	`lastUpdatedBy` integer,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `clients` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`userId` integer NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`phone` text,
	`company` text,
	`address` text,
	`taxId` text,
	`status` text DEFAULT 'active' NOT NULL,
	`workflowStatus` text DEFAULT 'new_lead' NOT NULL,
	`leadSource` text,
	`discoveryDate` integer,
	`nextAction` text,
	`nextActionDate` integer,
	`painPoints` text,
	`expectations` text,
	`serviceTier` text DEFAULT 'standard',
	`monthlyFee` real DEFAULT 0,
	`onboardingSentAt` integer,
	`onboardingCompletedAt` integer,
	`onboardingToken` text,
	`assignedTo` text,
	`notes` text,
	`googleDriveFolderId` text,
	`oneDriveFolderId` text,
	`qboCustomerId` text,
	`qboConnectionId` integer,
	`createdAt` integer,
	`updatedAt` integer
);
INSERT INTO "clients" VALUES(1,1,'12738988 Canada Inc','12738988_canada_inc@placeholder.local',NULL,NULL,NULL,'781088661','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Markie','Registry #: 1001352299
Corp Type: Federal Business Corp
Incorporated: 2024-09-20
Legal Name: 12738988 CANADA INC.
Federal corporation; Annual reporting; YE: Dec',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370380','2026-05-14T01:25:10.300482');
INSERT INTO "clients" VALUES(2,1,'Universal Construction','Universalconstructionyeg1605@gmail.com','(416) 722-9447',NULL,'Woodbridge, ON L4H 1N6','741962930','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Markie','Registry #: 2747411
Corp Type: Ontario Business Corp
Incorporated: 2020-03-10
Legal Name: UNIVERSAL CONSTRUCTION GROUP INC.
GOT GOVT DATA; Ontario-based; Weekly payroll; YE: Dec',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370598','2026-05-14T01:25:10.299959');
INSERT INTO "clients" VALUES(3,1,'Columbus Cafe','columbus_cafe@placeholder.local',NULL,NULL,NULL,'758960231','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Brad','Close: Monthly, HST: Qrtly',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370617','2026-05-14T01:19:56.370617');
INSERT INTO "clients" VALUES(4,1,'Align by Design Inc','hello@alignanddesign.ca','(647) 200-3501',NULL,'Toronto, ON','707477733','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Amy','Registry #: 12404648
Corp Type: Federal Business Corp
Incorporated: 2020-10-08
Legal Name: ALIGN BY DESIGN HD INC.
GOT GOVT DATA; Federal corporation; Bi-weekly payroll; QBO 47.5; YE: Oct',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370628','2026-05-14T01:25:10.299984');
INSERT INTO "clients" VALUES(5,1,'Ovita Construction','ovita_construction@placeholder.local','(905) 851-7744',NULL,'6260 Highway 7, Unit 7, Vaughan, ON L4H 4G3','752504498','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Rocco','Registry #: 2536157
Corp Type: Ontario Business Corp
Incorporated: 2016-09-12
Legal Name: OVITA CONSTRUCTION LTD.
GOT GOVT DATA; Also: 40 Great Gulf Dr #33, Concord; WSIB Q2; YE: Nov',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370642','2026-05-14T01:25:10.299908');
INSERT INTO "clients" VALUES(6,1,'Ovita Holdings Inc','ovita_holdings_inc@placeholder.local',NULL,NULL,'Vaughan, ON','722717121','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Rocco','Registry #: 2567485
Corp Type: Ontario Business Corp
Incorporated: 2017-03-20
Legal Name: OVITA HOLDINGS INC.
GOT GOVT DATA; Related to Ovita Construction; YE: Dec',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370652','2026-05-14T01:25:10.299932');
INSERT INTO "clients" VALUES(7,1,'Darkhorse','darkhorse@placeholder.local','1-800-261-1832',NULL,NULL,'750383671','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Brad','Registry #: 2739028
Corp Type: Ontario Business Corp
Incorporated: 2020-01-24
Legal Name: DARK HORSE INTELLIGENCE INC.
GOT GOVT DATA; Legal name differs from DBA; Monthly payroll; WSIB Q4; YE: Dec',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370660','2026-05-14T01:25:10.300294');
INSERT INTO "clients" VALUES(8,1,'GoToMarket Agility Inc','gotomarket_agility_inc@placeholder.local',NULL,NULL,'Toronto, ON','817061252','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Brad','Registry #: 2240452
Corp Type: Ontario Business Corp
Incorporated: 2010-04-14
Legal Name: GOTOMARKET AGILITY INC.
GOT GOVT DATA; Focus on CPG industry; No HST/Payroll',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370670','2026-05-14T01:25:10.300020');
INSERT INTO "clients" VALUES(9,1,'Aim Construction Inc','aim_construction_inc@placeholder.local',NULL,NULL,NULL,'807649798','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: AIM CONSTRUCTION INC.
No registry data found; Annual reporting; YE: Dec',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370678','2026-05-14T01:25:10.300365');
INSERT INTO "clients" VALUES(10,1,'Selective Painting','selective_painting@placeholder.local',NULL,NULL,NULL,'784617565','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: SELECTIVE PAINTING INC.
No registry data found; Yearly reporting; YE: Dec',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370687','2026-05-14T01:25:10.300390');
INSERT INTO "clients" VALUES(11,1,'Fleming','fleming@placeholder.local',NULL,NULL,NULL,'803271337','inactive','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'John','Registry #: 2382835
Corp Type: Ontario Business Corp
Incorporated: 2013-07-31
CORP STATUS: Voluntary Dissolution
Legal Name: FLEMING Q.E.D. INC.
DISSOLVED per government registry 2013-07-31. Annual reporting. YE: Dec',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370695','2026-05-14T01:25:10.300886');
INSERT INTO "clients" VALUES(12,1,'Kaavio','kaavio@placeholder.local',NULL,NULL,NULL,'736845488','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'John','Close: Annual, YE: Dec, HST: Annual',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370705','2026-05-14T01:19:56.370705');
INSERT INTO "clients" VALUES(13,1,'Osteoathics','osteoathics@placeholder.local',NULL,NULL,NULL,'809545346','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: OSTEOATHICS
No registry data found',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370713','2026-05-14T01:25:10.300414');
INSERT INTO "clients" VALUES(14,1,'Originality.AI Inc','originalityai_inc@placeholder.local',NULL,NULL,NULL,'786440610','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Jon','Close: Monthly, YE: Sept, HST: Qrtly, T4 2024, Stripe/Paypal, QBO 47.5, Payroll: Monthly',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370723','2026-05-14T01:19:56.370723');
INSERT INTO "clients" VALUES(15,1,'Clark Pools Collingwood','office@clarkpoolscollingwood.com','(705) 445-6165',NULL,'20 Balsam St, Collingwood, ON L9Y 4H7','770298602','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Jon','Registry #: 1000001017
Corp Type: Ontario Business Corp
Incorporated: 2021-10-19
Legal Name: CLARK POOLS AND SPAS COLLINGWOOD INC.
GOT GOVT DATA; Bi-weekly payroll; WSIB Q4; Square/Jobber',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370733','2026-05-14T01:25:10.299466');
INSERT INTO "clients" VALUES(16,1,'West York Paving Ltd','west_york_paving@placeholder.local','(416) 231-6394 / 1-800-317-9558',NULL,'200 Rexdale Blvd, Etobicoke, ON M9W 1R2 / 13815 Highway 27, Nobleton, ON','877933515','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Markie','Registry #: 1491517
Corp Type: Ontario Business Corp
Incorporated: 2001-09-04
Legal Name: WEST YORK PAVING LTD.
GOT GOVT DATA; Weekly payroll; WSIB Q4; YE: Dec',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370741','2026-05-14T01:25:10.299784');
INSERT INTO "clients" VALUES(17,1,'The Auld Spot Pub','the_auld_spot_pub@placeholder.local','(416) 461-1114 / (416) 406-4688',NULL,'347 Danforth Ave, Toronto, ON M4K 1N7','718843600','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Markie','Registry #: 1000235299
Corp Type: Ontario Business Corp
Incorporated: 2022-06-16
Legal Name: 1000235299 ONTARIO LTD. (The Auld Spot Pub)
GOT GOVT DATA; DBA: The Auld Spot Pub; TouchBistro POS; Bi-weekly payroll; WSIB Q4; YE: Sept',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370750','2026-05-14T01:25:10.299818');
INSERT INTO "clients" VALUES(18,1,'King Industries Inc','king_industries_inc@placeholder.local','(877) 289-3625',NULL,'29 Nobel Rd, McDougall, ON P2A 2W9','858977705','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Brad','Registry #: 6206522
Corp Type: Federal Business Corp
Incorporated: 2004-03-12
Legal Name: KING INDUSTRIES INC.
GOT GOVT DATA; Includes Dock Kings division; WSIB Q2; QBO 47.5; YE: Dec',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370759','2026-05-14T01:25:10.299871');
INSERT INTO "clients" VALUES(19,1,'Studio Lella Inc','studiolellainc@gmail.com','(905) 893-5550',NULL,'110 Nashville Rd, Unit 10, Kleinburg, ON L0J 1C0','792026429','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Anthony','Registry #: 1000816710
Corp Type: Ontario Business Corp
Incorporated: 2024-02-29
Legal Name: STUDIO LELLA INC.
GOT GOVT DATA; Quarterly reporting; Self payroll; YE: Dec',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370779','2026-05-14T01:25:10.300265');
INSERT INTO "clients" VALUES(20,1,'Laing Scientific','laing_scientific@placeholder.local',NULL,NULL,NULL,'127437374','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: LAING SCIENTIFIC
No registry data found; Quarterly reporting; QBO 22.4; YE: Dec',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370788','2026-05-14T01:25:10.300437');
INSERT INTO "clients" VALUES(21,1,'Align Plumbing','align_plumbing@placeholder.local',NULL,NULL,NULL,'789978301','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: ALIGN PLUMBING INC.
CRA found but no full registry data; Monthly payroll; YE: July',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370798','2026-05-14T01:25:10.300329');
INSERT INTO "clients" VALUES(22,1,'2303851 Ontario Inc','2303851_ontario_inc@placeholder.local',NULL,NULL,NULL,'847759909','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Jon','Registry #: 2303851
Corp Type: Ontario Business Corp
Incorporated: 2011-10-28
Legal Name: 2303851 ONTARIO INC.
GOT GOVT DATA; Monthly reporting; Stripe/PayPal; QBO 47.5; Threshold 1; YE: Sept',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370807','2026-05-14T01:25:10.300235');
INSERT INTO "clients" VALUES(23,1,'Clark Pools Owen Sound','info@clarkpools.com','(519) 372-9411',NULL,'718028 Hwy 6, Owen Sound, ON N4K 5N7','715666566','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Jon','Registry #: 1001447196
Corp Type: Ontario Business Corp
Incorporated: 2025-12-17
Legal Name: CLARK POOLS AND SPAS OWEN SOUND INC.
GOT GOVT DATA; Related to Clark Pools Collingwood; WSIB Q4; Square/Jobber',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370828','2026-05-14T01:25:10.299714');
INSERT INTO "clients" VALUES(24,1,'Motion Invest Inc','contact@motioninvest.com',NULL,NULL,'1 First Street, Collingwood, ON L9Y 1A1','728898321','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Jon','Registry #: 2560628
Corp Type: Ontario Business Corp
Incorporated: 2017-02-09
Legal Name: MOTION INVEST INC.
GOT GOVT DATA; Monthly reporting; Stripe/PayPal; YE: Sept',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370838','2026-05-14T01:25:10.300073');
INSERT INTO "clients" VALUES(25,1,'Fractal SaaS Inc','andrew@passed.ai',NULL,NULL,'64 Hurontario St, Suite 200, Collingwood, ON L9Y 2L6','739247070','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Jon','Registry #: 2750934
Corp Type: Ontario Business Corp
Incorporated: 2020-04-03
Legal Name: FRACTAL SAAS INC.
GOT GOVT DATA; Monthly reporting; Stripe/Duey; QBO 47.5; YE: Sept',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370847','2026-05-14T01:25:10.300095');
INSERT INTO "clients" VALUES(26,1,'Adbank Inc','hello@adbank.network',NULL,NULL,'Collingwood, ON L9Y 1A1','793523481','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Jon','Registry #: 2597757
Corp Type: Ontario Business Corp
Incorporated: 2017-09-20
Legal Name: ADBANK INC.
GOT GOVT DATA; Monthly reporting; Paypal; QBO 47.5; YE: Sept',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370856','2026-05-14T01:25:10.300050');
INSERT INTO "clients" VALUES(27,1,'Listing Eagle','listing_eagle@placeholder.local',NULL,NULL,NULL,'767302490','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Jon','Registry #: 2520953
Corp Type: Ontario Business Corp
Incorporated: 2016-05-31
Legal Name: LISTINGEAGLE.COM INC.
GOT GOVT DATA; Annual reporting; QBO 32.5; YE: Sept',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370866','2026-05-14T01:25:10.300118');
INSERT INTO "clients" VALUES(28,1,'Marketing Strategy Ventures','marketing_strategy_ventures@placeholder.local',NULL,NULL,NULL,'763289337','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Jon','Registry #: 2724538
Corp Type: Ontario Business Corp
Incorporated: 2019-10-31
Legal Name: MARKETING STRATEGY VENTURES INC.
GOT GOVT DATA; Monthly reporting; Non-Resident; Stripe/PayPal; YE: Sept',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370876','2026-05-14T01:25:10.300141');
INSERT INTO "clients" VALUES(29,1,'Seahorse Health Inc','seahorse_health_inc@placeholder.local',NULL,NULL,NULL,'728509522','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Jon','Registry #: 2561240
Corp Type: Ontario Business Corp
Incorporated: 2017-02-13
Legal Name: SEAHORSE HEALTH INC.
GOT GOVT DATA; Annual reporting; Shopify; QBO 47.5; YE: Sept',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370885','2026-05-14T01:25:10.300165');
INSERT INTO "clients" VALUES(30,1,'Sher-E-Punjab','sher-e-punjab@placeholder.local','(416) 465-2125',NULL,'351 Danforth Ave, Toronto, ON M4K 1N7','706313020','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Markie','Registry #: 1001196626
Corp Type: Ontario Business Corp
Incorporated: 2025-04-03
Legal Name: 1001196626 ONTARIO LTD. (Sher-E-Punjab)
GOT GOVT DATA; DBA: Sher-E-Punjab; Bi-weekly payroll; T4 filed',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370895','2026-05-14T01:25:10.299845');
INSERT INTO "clients" VALUES(31,1,'Unimax Construction Group LLC','unimax_construction_group_llc@placeholder.local',NULL,NULL,'USA','USA','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: UNIMAX CONSTRUCTION GROUP LLC
US CLIENT - No Canadian registry; YE: Dec',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370904','2026-05-14T01:25:10.300508');
INSERT INTO "clients" VALUES(32,1,'M.M. Kapala','mm_kapala@placeholder.local',NULL,NULL,NULL,'827463951','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Marriana','Registry #: 1758046
Corp Type: Ontario Business Corp
Incorporated: 2007-12-19
Legal Name: M.M. KAPALA MEDICINE PROFESSIONAL CORPORATION
GOT GOVT DATA; Medicine Professional Corp; Annual reporting; YE: Jun',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370914','2026-05-14T01:25:10.300188');
INSERT INTO "clients" VALUES(33,1,'Alderson','alderson@placeholder.local','(905) 934-1372 / (780) 232-9092',NULL,'St Catharines, ON / Ottawa, ON','774355168','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'Rocco','Registry #: 1001174780
Corp Type: Ontario Business Corp
Incorporated: 2025-03-14
Legal Name: ALDERSON DEVELOPMENTS LTD.
GOT GOVT DATA; Annual reporting; Part of Ovita group; YE: Nov',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370925','2026-05-14T01:25:10.300213');
INSERT INTO "clients" VALUES(34,1,'Universal Drywall Systems','universal_drywall_systems@placeholder.local',NULL,NULL,'USA','USA','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: UNIVERSAL DRYWALL SYSTEMS
US CLIENT - No Canadian registry',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370934','2026-05-14T01:25:10.300460');
INSERT INTO "clients" VALUES(35,1,'Dock Kings','dock_kings@placeholder.local',NULL,NULL,NULL,NULL,'inactive','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','CORP STATUS: Inactive
Legal Name: DOCK KINGS
No CRA number; Division of King Industries',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370944','2026-05-14T01:25:10.300531');
INSERT INTO "clients" VALUES(36,1,'Pugtree','pugtree@placeholder.local',NULL,NULL,NULL,NULL,'active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: PUGTREE
No registry data',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370959','2026-05-14T01:25:10.300554');
INSERT INTO "clients" VALUES(37,1,'King Investments','king_investments@placeholder.local',NULL,NULL,NULL,NULL,'active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: KING INVESTMENTS
No registry data',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370970','2026-05-14T01:25:10.300576');
INSERT INTO "clients" VALUES(38,1,'MK','mk@placeholder.local',NULL,NULL,NULL,NULL,'active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','No registry data',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370984','2026-05-14T01:25:10.300598');
INSERT INTO "clients" VALUES(39,1,'Social Seed','social_seed@placeholder.local',NULL,NULL,NULL,NULL,'active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: SOCIAL SEED
No registry data',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.370996','2026-05-14T01:25:10.300621');
INSERT INTO "clients" VALUES(40,1,'Advanced Wallcoverings Inc','advanced_wallcoverings_inc@placeholder.local',NULL,NULL,NULL,'817578982','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: ADVANCED WALLCOVERINGS INC.
YE 2023; Annual reporting',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.371016','2026-05-14T01:25:10.300643');
INSERT INTO "clients" VALUES(41,1,'Brookebuilt Inc','brookebuilt_inc@placeholder.local','(416) 270-5578',NULL,'200 Beech Avenue, Toronto, ON M4E 3H9','810918953','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: BROOKEBUILT INC.
No registry data found; YE: Mar 2022',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.371028','2026-05-14T01:25:10.300665');
INSERT INTO "clients" VALUES(42,1,'Culbert''s Bakery Ltd','info.culbert@gmail.com','1-800-265-5594 / (519) 524-5321',NULL,'50 North St, Goderich, ON N7A 2T4','705597706','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: CULBERT''S BAKERY LTD.
CRA: 705597706; Bi-weekly payroll; YE: Sept 2022',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.371038','2026-05-14T01:25:10.300687');
INSERT INTO "clients" VALUES(43,1,'Damiva Canada','hello@damiva.com','1-800-311-1532',NULL,'20 Great Gulf Drive, Unit 14, Vaughan, ON L4K 0K7','816511489','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: DAMIVA CANADA
CRA: 816511489; YE: Dec 2022',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.371049','2026-05-14T01:25:10.300709');
INSERT INTO "clients" VALUES(44,1,'Lemysta Systems','lemysta_systems@placeholder.local',NULL,NULL,NULL,'874004823','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: LEMYSTA SYSTEMS
CRA: 874004823; Quarterly reporting; YE: Sept 2022',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.371060','2026-05-14T01:25:10.300731');
INSERT INTO "clients" VALUES(45,1,'MRM Software Inc','sales@mrmsoftinc.com','(281) 899-0568',NULL,NULL,'718820681','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: MRM SOFTWARE INC.
CRA: 718820681; YE: Dec 2022',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.371070','2026-05-14T01:25:10.300752');
INSERT INTO "clients" VALUES(46,1,'StarCluster','starcluster@placeholder.local',NULL,NULL,NULL,'708679923','inactive','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','CORP STATUS: Inactive
Legal Name: STARCLUSTER
CRA: 708679923; YE: Apr 2023',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.371081','2026-05-14T01:25:10.300775');
INSERT INTO "clients" VALUES(47,1,'Thames Valley Brick & Tile','info@thamesvalleybrick.com','(905) 637-6997 / 1-800-567-5800',NULL,'#9-5115 Harvester Rd, Burlington, ON L7L 0A3','867688335','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','CORP STATUS: Inactive
Legal Name: THAMES VALLEY BRICK & TILE
CRA: 867688335; YE: Dec 2022',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.371092','2026-05-14T01:25:10.300798');
INSERT INTO "clients" VALUES(48,1,'TVB Hold Co','tvb_hold_co@placeholder.local',NULL,NULL,NULL,'837599380','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: TVB HOLD CO
CRA: 837599380',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.371103','2026-05-14T01:25:10.300820');
INSERT INTO "clients" VALUES(49,1,'Prosperity Place','prosperity_place@placeholder.local',NULL,NULL,'USA','USA','active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','CORP STATUS: Inactive
Legal Name: PROSPERITY PLACE
US CLIENT; Formerly active',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.371114','2026-05-14T01:25:10.300841');
INSERT INTO "clients" VALUES(50,1,'Vision Marketing Associates','vision_marketing_associates@placeholder.local',NULL,NULL,NULL,NULL,'active','new_lead',NULL,NULL,NULL,NULL,NULL,NULL,'standard',0.0,NULL,NULL,NULL,'N/A','Legal Name: VISION MARKETING ASSOCIATES
No registry data',NULL,NULL,NULL,NULL,'2026-05-14T01:19:56.371125','2026-05-14T01:25:10.300863');
CREATE TABLE `connected_accounts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`userId` integer NOT NULL,
	`provider` text NOT NULL,
	`providerAccountId` text NOT NULL,
	`accountLabel` text DEFAULT 'Primary' NOT NULL,
	`accountEmail` text,
	`accessToken` text,
	`refreshToken` text,
	`expiresAt` integer,
	`scopes` text,
	`isActive` integer DEFAULT true NOT NULL,
	`syncEnabled` text DEFAULT '{"email":true,"calendar":true,"files":true,"tasks":true}',
	`lastSyncedAt` integer,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `emails` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`userId` integer NOT NULL,
	`connectedAccountId` integer NOT NULL,
	`clientId` integer,
	`gmailMessageId` text,
	`outlookMessageId` text,
	`threadId` text,
	`fromAddress` text NOT NULL,
	`fromName` text,
	`replyTo` text,
	`toAddresses` text NOT NULL,
	`ccAddresses` text,
	`subject` text,
	`body` text,
	`bodyPlain` text,
	`isRead` integer DEFAULT false NOT NULL,
	`isStarred` integer DEFAULT false NOT NULL,
	`isImportant` integer DEFAULT false NOT NULL,
	`isSent` integer DEFAULT false NOT NULL,
	`inReplyTo` integer,
	`labels` text,
	`attachments` text,
	`receivedAt` integer NOT NULL,
	`sentAt` integer,
	`createdAt` integer
);
CREATE TABLE `employees` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`firstName` text NOT NULL,
	`lastName` text NOT NULL,
	`sin` text,
	`dateOfBirth` integer,
	`hireDate` integer,
	`startDate` integer,
	`payType` text DEFAULT 'salary',
	`annualSalary` real,
	`hourlyRate` real,
	`hoursPerWeek` real DEFAULT 40,
	`position` text,
	`department` text,
	`email` text,
	`phone` text,
	`address` text,
	`isContractor` integer DEFAULT false,
	`isActive` integer DEFAULT true,
	`terminationDate` integer,
	`terminationReason` text,
	`hasHealthBenefits` integer DEFAULT false,
	`hasDentalBenefits` integer DEFAULT false,
	`hasRrsp` integer DEFAULT false,
	`rrspMatchPercent` real,
	`onGovernmentGrant` integer DEFAULT false,
	`grantType` text,
	`grantStartDate` integer,
	`grantEndDate` integer,
	`federalTaxCredits` text,
	`provincialTaxCredits` text,
	`t4Box14Wages` real,
	`t4Box16Cpp` real,
	`t4Box18Ei` real,
	`t4Box20Rpp` real,
	`t4Box44UnionDues` real,
	`t4Box46Charitable` real,
	`notes` text,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `engagement_letters` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`templateName` text DEFAULT 'standard',
	`title` text NOT NULL,
	`content` text NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`sentAt` integer,
	`viewedAt` integer,
	`signedAt` integer,
	`signedBy` text,
	`sentBy` integer,
	`monthlyFee` real,
	`hourlyRate` real,
	`retainerAmount` real,
	`servicesIncluded` text,
	`servicesExcluded` text,
	`termStart` integer,
	`termEnd` integer,
	`autoRenew` integer DEFAULT true,
	`renewalNoticeDays` integer DEFAULT 30,
	`jurisdiction` text DEFAULT 'Ontario, Canada',
	`governingLaw` text DEFAULT 'Laws of the Province of Ontario and the federal laws of Canada',
	`notes` text,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `files` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`userId` integer NOT NULL,
	`clientId` integer,
	`connectedAccountId` integer,
	`provider` text NOT NULL,
	`providerFileId` text,
	`providerParentId` text,
	`name` text NOT NULL,
	`mimeType` text,
	`size` integer,
	`webViewLink` text,
	`downloadLink` text,
	`thumbnailLink` text,
	`isFolder` integer DEFAULT false NOT NULL,
	`localPath` text,
	`syncStatus` text DEFAULT 'synced' NOT NULL,
	`lastSyncedAt` integer,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `interactions` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`userId` integer NOT NULL,
	`clientId` integer NOT NULL,
	`type` text NOT NULL,
	`date` integer NOT NULL,
	`notes` text,
	`assignedTo` text,
	`followUpDate` integer,
	`emailId` integer,
	`calendarEventId` integer,
	`createdAt` integer
);
CREATE TABLE `invoice_items` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`invoiceId` integer NOT NULL,
	`description` text NOT NULL,
	`quantity` real DEFAULT 1 NOT NULL,
	`rate` real NOT NULL,
	`amount` real NOT NULL,
	`createdAt` integer
);
CREATE TABLE `invoices` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`userId` integer NOT NULL,
	`clientId` integer NOT NULL,
	`qboInvoiceId` text,
	`invoiceNumber` text NOT NULL,
	`amount` real NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`issueDate` integer NOT NULL,
	`dueDate` integer NOT NULL,
	`paidDate` integer,
	`description` text,
	`notes` text,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `missing_items` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`userId` integer NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`category` text DEFAULT 'other' NOT NULL,
	`dueDate` integer,
	`status` text DEFAULT 'pending' NOT NULL,
	`uploadedFileId` integer,
	`submittedAt` integer,
	`reviewedAt` integer,
	`notes` text,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `monthly_close_checklist` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`userId` integer NOT NULL,
	`year` integer NOT NULL,
	`month` integer NOT NULL,
	`bankStatementsReconciled` integer DEFAULT false NOT NULL,
	`creditCardStatementsReconciled` integer DEFAULT false NOT NULL,
	`allReceiptsProcessed` integer DEFAULT false NOT NULL,
	`apReviewed` integer DEFAULT false NOT NULL,
	`arReviewed` integer DEFAULT false NOT NULL,
	`payrollJournalVerified` integer DEFAULT false NOT NULL,
	`sourceDeductionsConfirmed` integer DEFAULT false NOT NULL,
	`hstGstTracked` integer DEFAULT false NOT NULL,
	`ownerTransactionsSeparated` integer DEFAULT false NOT NULL,
	`adjustingEntriesPosted` integer DEFAULT false NOT NULL,
	`plReviewed` integer DEFAULT false NOT NULL,
	`balanceSheetReviewed` integer DEFAULT false NOT NULL,
	`bankRecMatchesBalanceSheet` integer DEFAULT false NOT NULL,
	`financialsUploaded` integer DEFAULT false NOT NULL,
	`clientNotified` integer DEFAULT false NOT NULL,
	`sourceDocsFiled` integer DEFAULT false NOT NULL,
	`notes` text,
	`completedAt` integer,
	`completionPercent` integer DEFAULT 0 NOT NULL,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `notifications` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`userId` integer NOT NULL,
	`type` text NOT NULL,
	`title` text NOT NULL,
	`message` text,
	`relatedId` integer,
	`relatedType` text,
	`isRead` integer DEFAULT false NOT NULL,
	`sentVia` text DEFAULT 'in_app' NOT NULL,
	`createdAt` integer
);
CREATE TABLE `portal_files` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`userId` integer NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`provider` text NOT NULL,
	`providerFileId` text,
	`webViewLink` text,
	`downloadLink` text,
	`mimeType` text,
	`size` integer,
	`category` text DEFAULT 'general' NOT NULL,
	`periodStart` integer,
	`periodEnd` integer,
	`isVisible` integer DEFAULT true NOT NULL,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `portal_settings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`showFinancialOverview` integer DEFAULT true NOT NULL,
	`showTasks` integer DEFAULT true NOT NULL,
	`showDocuments` integer DEFAULT true NOT NULL,
	`showInvoices` integer DEFAULT true NOT NULL,
	`showTaxDeadlines` integer DEFAULT false NOT NULL,
	`welcomeMessage` text,
	`isEnabled` integer DEFAULT false NOT NULL,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `portal_tokens` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`token` text NOT NULL,
	`email` text NOT NULL,
	`isActive` integer DEFAULT true NOT NULL,
	`expiresAt` integer,
	`lastUsedAt` integer,
	`createdAt` integer
);
CREATE TABLE `qbo_accounts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`connectionId` integer NOT NULL,
	`qboAccountId` text NOT NULL,
	`name` text,
	`accountType` text,
	`accountSubType` text,
	`classification` text,
	`currentBalance` real DEFAULT 0,
	`currencyRef` text,
	`active` integer DEFAULT true,
	`lastUpdatedAt` integer,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `qbo_connections` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`userId` integer NOT NULL,
	`realmId` text NOT NULL,
	`companyName` text,
	`companyEmail` text,
	`accessToken` text,
	`refreshToken` text,
	`expiresAt` integer,
	`environment` text DEFAULT 'sandbox' NOT NULL,
	`accountType` text DEFAULT 'ca_clients' NOT NULL,
	`isActive` integer DEFAULT true NOT NULL,
	`lastSyncedAt` integer,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `qbo_customers` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`connectionId` integer NOT NULL,
	`qboCustomerId` text NOT NULL,
	`clientId` integer,
	`displayName` text,
	`companyName` text,
	`givenName` text,
	`familyName` text,
	`email` text,
	`phone` text,
	`mobile` text,
	`fax` text,
	`addressLine1` text,
	`addressLine2` text,
	`city` text,
	`state` text,
	`postalCode` text,
	`country` text,
	`balance` real DEFAULT 0,
	`taxable` integer DEFAULT true,
	`active` integer DEFAULT true,
	`driveFolderUrl` text,
	`quickLinks` text,
	`monthlyFee` real,
	`hourlyRate` real,
	`billingType` text,
	`lastReconciledDate` integer,
	`booksHealthScore` integer DEFAULT 100,
	`lastHstFiled` integer,
	`lastPayrollRemitted` integer,
	`isUsClient` integer DEFAULT false,
	`usTaxId` text,
	`qboAccountType` text DEFAULT 'ca_clients',
	`notes` text,
	`lastUpdatedAt` integer,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `qbo_invoices` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`connectionId` integer NOT NULL,
	`qboInvoiceId` text NOT NULL,
	`qboCustomerId` text,
	`clientId` integer,
	`invoiceNumber` text,
	`docNumber` text,
	`transactionDate` integer,
	`dueDate` integer,
	`totalAmount` real DEFAULT 0,
	`balance` real DEFAULT 0,
	`status` text DEFAULT 'draft',
	`lineItems` text,
	`memo` text,
	`privateNote` text,
	`lastUpdatedAt` integer,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `qbo_payments` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`connectionId` integer NOT NULL,
	`qboPaymentId` text NOT NULL,
	`qboCustomerId` text,
	`clientId` integer,
	`totalAmount` real DEFAULT 0,
	`unappliedAmount` real DEFAULT 0,
	`paymentMethod` text,
	`transactionDate` integer,
	`status` text,
	`memo` text,
	`lastUpdatedAt` integer,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `qbo_sync_logs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`connectionId` integer NOT NULL,
	`entityType` text NOT NULL,
	`status` text NOT NULL,
	`recordsSynced` integer DEFAULT 0 NOT NULL,
	`errorMessage` text,
	`startedAt` integer,
	`completedAt` integer
);
CREATE TABLE `recurring_tasks` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`userId` integer NOT NULL,
	`clientId` integer,
	`title` text NOT NULL,
	`description` text,
	`frequency` text NOT NULL,
	`startDate` integer NOT NULL,
	`endDate` integer,
	`priority` text DEFAULT 'medium' NOT NULL,
	`category` text,
	`assignedTo` text,
	`lastGeneratedDate` integer,
	`nextDueDate` integer NOT NULL,
	`active` integer DEFAULT true NOT NULL,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `satisfaction_scores` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`userId` integer NOT NULL,
	`score` integer NOT NULL,
	`notes` text,
	`callType` text DEFAULT 'check_in',
	`createdAt` integer
);
CREATE TABLE `signature_documents` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`userId` integer NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`content` text NOT NULL,
	`documentType` text DEFAULT 'custom' NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`signedBy` text,
	`signedByEmail` text,
	`signatureType` text DEFAULT 'type_name',
	`signatureData` text,
	`signedAt` integer,
	`ipAddress` text,
	`portalToken` text,
	`expiresAt` integer,
	`sentAt` integer,
	`viewedAt` integer,
	`sentBy` integer,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `tasks` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`userId` integer NOT NULL,
	`clientId` integer,
	`title` text NOT NULL,
	`description` text,
	`dueDate` integer,
	`completed` integer DEFAULT false NOT NULL,
	`completedAt` integer,
	`priority` text DEFAULT 'medium' NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`category` text,
	`assignedTo` text,
	`ruleId` integer,
	`isRecurring` integer DEFAULT false,
	`recurrenceCount` integer DEFAULT 1,
	`googleCalendarEventId` text,
	`googleTaskId` text,
	`outlookTaskId` text,
	`createdAt` integer,
	`updatedAt` integer
);
INSERT INTO "tasks" VALUES(1,1,1,'Year-End Close (Dec) - 12738988 Canada Inc','Year-end bookkeeping close for 12738988 Canada Inc (YE: Dec). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Markie',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339189','2026-05-14T01:27:29.339189');
INSERT INTO "tasks" VALUES(2,1,2,'Payroll - Universal Construction','Weekly payroll processing for Universal Construction. Calculate wages, deductions, prepare pay stubs, remit source deductions.',NULL,0,NULL,'high','pending','Payroll','Markie',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339426','2026-05-14T01:27:29.339426');
INSERT INTO "tasks" VALUES(3,1,2,'Year-End Close (Dec) - Universal Construction','Year-end bookkeeping close for Universal Construction (YE: Dec). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Markie',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339426','2026-05-14T01:27:29.339426');
INSERT INTO "tasks" VALUES(4,1,2,'T4 Preparation - Universal Construction','Annual T4 and T4 Summary preparation for Universal Construction. Prepare employee T4s, file with CRA, distribute to employees.',NULL,0,NULL,'high','pending','T4/Tax','Markie',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339426','2026-05-14T01:27:29.339426');
INSERT INTO "tasks" VALUES(5,1,3,'Monthly Close - Columbus Cafe','Monthly bookkeeping close for Columbus Cafe. Reconcile accounts, review transactions, ensure all entries posted.',NULL,0,NULL,'high','pending','Monthly Close','Brad',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339465','2026-05-14T01:27:29.339465');
INSERT INTO "tasks" VALUES(6,1,3,'HST Filing - Columbus Cafe','Quarterly HST filing for Columbus Cafe. Prepare HST return, review ITCs, file with CRA.',NULL,0,NULL,'high','pending','HST Filing','Brad',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339465','2026-05-14T01:27:29.339465');
INSERT INTO "tasks" VALUES(7,1,4,'Payroll - Align by Design Inc','Bi-weekly payroll processing for Align by Design Inc. Calculate wages, deductions, prepare pay stubs, remit source deductions.',NULL,0,NULL,'high','pending','Payroll','Amy',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339488','2026-05-14T01:27:29.339488');
INSERT INTO "tasks" VALUES(8,1,4,'Year-End Close (Oct) - Align by Design Inc','Year-end bookkeeping close for Align by Design Inc (YE: Oct). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Amy',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339488','2026-05-14T01:27:29.339488');
INSERT INTO "tasks" VALUES(9,1,4,'T4 Preparation - Align by Design Inc','Annual T4 and T4 Summary preparation for Align by Design Inc. Prepare employee T4s, file with CRA, distribute to employees.',NULL,0,NULL,'high','pending','T4/Tax','Amy',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339488','2026-05-14T01:27:29.339488');
INSERT INTO "tasks" VALUES(10,1,5,'WSIB Filing (due Q2) - Ovita Construction','WSIB quarterly filing (due Q2) for Ovita Construction. Calculate premiums, prepare return, submit to WSIB. (due Q2)',NULL,0,NULL,'medium','pending','WSIB','Rocco',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339514','2026-05-14T01:27:29.339514');
INSERT INTO "tasks" VALUES(11,1,5,'Year-End Close (Nov) - Ovita Construction','Year-end bookkeeping close for Ovita Construction (YE: Nov). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Rocco',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339514','2026-05-14T01:27:29.339514');
INSERT INTO "tasks" VALUES(12,1,6,'Year-End Close (Dec) - Ovita Holdings Inc','Year-end bookkeeping close for Ovita Holdings Inc (YE: Dec). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Rocco',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339537','2026-05-14T01:27:29.339537');
INSERT INTO "tasks" VALUES(13,1,7,'Payroll - Darkhorse','Monthly payroll processing for Darkhorse. Calculate wages, deductions, prepare pay stubs, remit source deductions.',NULL,0,NULL,'high','pending','Payroll','Brad',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339555','2026-05-14T01:27:29.339555');
INSERT INTO "tasks" VALUES(14,1,7,'WSIB Filing (due Q4) - Darkhorse','WSIB quarterly filing (due Q4) for Darkhorse. Calculate premiums, prepare return, submit to WSIB. (due Q4)',NULL,0,NULL,'medium','pending','WSIB','Brad',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339555','2026-05-14T01:27:29.339555');
INSERT INTO "tasks" VALUES(15,1,7,'Year-End Close (Dec) - Darkhorse','Year-end bookkeeping close for Darkhorse (YE: Dec). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Brad',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339555','2026-05-14T01:27:29.339555');
INSERT INTO "tasks" VALUES(16,1,7,'T4 Preparation - Darkhorse','Annual T4 and T4 Summary preparation for Darkhorse. Prepare employee T4s, file with CRA, distribute to employees.',NULL,0,NULL,'high','pending','T4/Tax','Brad',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339555','2026-05-14T01:27:29.339555');
INSERT INTO "tasks" VALUES(17,1,9,'Year-End Close (Dec) - Aim Construction Inc','Year-end bookkeeping close for Aim Construction Inc (YE: Dec). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339610','2026-05-14T01:27:29.339610');
INSERT INTO "tasks" VALUES(18,1,10,'Year-End Close (Dec) - Selective Painting','Year-end bookkeeping close for Selective Painting (YE: Dec). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339637','2026-05-14T01:27:29.339637');
INSERT INTO "tasks" VALUES(19,1,12,'HST Filing - Kaavio','Annual HST filing for Kaavio. Prepare annual HST return, review ITCs, file with CRA.',NULL,0,NULL,'high','pending','HST Filing','John',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339651','2026-05-14T01:27:29.339651');
INSERT INTO "tasks" VALUES(20,1,12,'Year-End Close (Dec) - Kaavio','Year-end bookkeeping close for Kaavio (YE: Dec). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','John',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339651','2026-05-14T01:27:29.339651');
INSERT INTO "tasks" VALUES(21,1,14,'Monthly Close - Originality.AI Inc','Monthly bookkeeping close for Originality.AI Inc. Reconcile accounts, review transactions, ensure all entries posted.',NULL,0,NULL,'high','pending','Monthly Close','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339679','2026-05-14T01:27:29.339679');
INSERT INTO "tasks" VALUES(22,1,14,'HST Filing - Originality.AI Inc','Quarterly HST filing for Originality.AI Inc. Prepare HST return, review ITCs, file with CRA.',NULL,0,NULL,'high','pending','HST Filing','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339679','2026-05-14T01:27:29.339679');
INSERT INTO "tasks" VALUES(23,1,14,'Payroll - Originality.AI Inc','Monthly payroll processing for Originality.AI Inc. Calculate wages, deductions, prepare pay stubs, remit source deductions.',NULL,0,NULL,'high','pending','Payroll','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339679','2026-05-14T01:27:29.339679');
INSERT INTO "tasks" VALUES(24,1,14,'Year-End Close (Sept) - Originality.AI Inc','Year-end bookkeeping close for Originality.AI Inc (YE: Sept). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339679','2026-05-14T01:27:29.339679');
INSERT INTO "tasks" VALUES(25,1,14,'T4 Preparation - Originality.AI Inc','Annual T4 and T4 Summary preparation for Originality.AI Inc. Prepare employee T4s, file with CRA, distribute to employees.',NULL,0,NULL,'high','pending','T4/Tax','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339679','2026-05-14T01:27:29.339679');
INSERT INTO "tasks" VALUES(26,1,15,'Payroll - Clark Pools Collingwood','Bi-weekly payroll processing for Clark Pools Collingwood. Calculate wages, deductions, prepare pay stubs, remit source deductions.',NULL,0,NULL,'high','pending','Payroll','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339710','2026-05-14T01:27:29.339710');
INSERT INTO "tasks" VALUES(27,1,15,'WSIB Filing (due Q4) - Clark Pools Collingwood','WSIB quarterly filing (due Q4) for Clark Pools Collingwood. Calculate premiums, prepare return, submit to WSIB. (due Q4)',NULL,0,NULL,'medium','pending','WSIB','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339710','2026-05-14T01:27:29.339710');
INSERT INTO "tasks" VALUES(28,1,15,'T4 Preparation - Clark Pools Collingwood','Annual T4 and T4 Summary preparation for Clark Pools Collingwood. Prepare employee T4s, file with CRA, distribute to employees.',NULL,0,NULL,'high','pending','T4/Tax','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339710','2026-05-14T01:27:29.339710');
INSERT INTO "tasks" VALUES(29,1,16,'Payroll - West York Paving Ltd','Weekly payroll processing for West York Paving Ltd. Calculate wages, deductions, prepare pay stubs, remit source deductions.',NULL,0,NULL,'high','pending','Payroll','Markie',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339734','2026-05-14T01:27:29.339734');
INSERT INTO "tasks" VALUES(30,1,16,'WSIB Filing (due Q4) - West York Paving Ltd','WSIB quarterly filing (due Q4) for West York Paving Ltd. Calculate premiums, prepare return, submit to WSIB. (due Q4)',NULL,0,NULL,'medium','pending','WSIB','Markie',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339734','2026-05-14T01:27:29.339734');
INSERT INTO "tasks" VALUES(31,1,16,'Year-End Close (Dec) - West York Paving Ltd','Year-end bookkeeping close for West York Paving Ltd (YE: Dec). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Markie',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339734','2026-05-14T01:27:29.339734');
INSERT INTO "tasks" VALUES(32,1,16,'T4 Preparation - West York Paving Ltd','Annual T4 and T4 Summary preparation for West York Paving Ltd. Prepare employee T4s, file with CRA, distribute to employees.',NULL,0,NULL,'high','pending','T4/Tax','Markie',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339734','2026-05-14T01:27:29.339734');
INSERT INTO "tasks" VALUES(33,1,17,'Payroll - The Auld Spot Pub','Bi-weekly payroll processing for The Auld Spot Pub. Calculate wages, deductions, prepare pay stubs, remit source deductions.',NULL,0,NULL,'high','pending','Payroll','Markie',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339762','2026-05-14T01:27:29.339762');
INSERT INTO "tasks" VALUES(34,1,17,'WSIB Filing (due Q4) - The Auld Spot Pub','WSIB quarterly filing (due Q4) for The Auld Spot Pub. Calculate premiums, prepare return, submit to WSIB. (due Q4)',NULL,0,NULL,'medium','pending','WSIB','Markie',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339762','2026-05-14T01:27:29.339762');
INSERT INTO "tasks" VALUES(35,1,17,'Year-End Close (Sept) - The Auld Spot Pub','Year-end bookkeeping close for The Auld Spot Pub (YE: Sept). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Markie',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339762','2026-05-14T01:27:29.339762');
INSERT INTO "tasks" VALUES(36,1,17,'T4 Preparation - The Auld Spot Pub','Annual T4 and T4 Summary preparation for The Auld Spot Pub. Prepare employee T4s, file with CRA, distribute to employees.',NULL,0,NULL,'high','pending','T4/Tax','Markie',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339762','2026-05-14T01:27:29.339762');
INSERT INTO "tasks" VALUES(37,1,18,'WSIB Filing (due Q2) - King Industries Inc','WSIB quarterly filing (due Q2) for King Industries Inc. Calculate premiums, prepare return, submit to WSIB. (due Q2)',NULL,0,NULL,'medium','pending','WSIB','Brad',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339789','2026-05-14T01:27:29.339789');
INSERT INTO "tasks" VALUES(38,1,18,'Year-End Close (Dec) - King Industries Inc','Year-end bookkeeping close for King Industries Inc (YE: Dec). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Brad',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339789','2026-05-14T01:27:29.339789');
INSERT INTO "tasks" VALUES(39,1,19,'Quarterly Close - Studio Lella Inc','Quarterly bookkeeping close for Studio Lella Inc. Prepare financial reports, review QBO entries, reconcile statements.',NULL,0,NULL,'high','pending','Quarterly Close','Anthony',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339811','2026-05-14T01:27:29.339811');
INSERT INTO "tasks" VALUES(40,1,19,'Payroll - Studio Lella Inc','Self-employed payroll processing for Studio Lella Inc. Owner draws, tax installments.',NULL,0,NULL,'high','pending','Payroll','Anthony',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339811','2026-05-14T01:27:29.339811');
INSERT INTO "tasks" VALUES(41,1,19,'Year-End Close (Dec) - Studio Lella Inc','Year-end bookkeeping close for Studio Lella Inc (YE: Dec). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Anthony',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339811','2026-05-14T01:27:29.339811');
INSERT INTO "tasks" VALUES(42,1,20,'Quarterly Close - Laing Scientific','Quarterly bookkeeping close for Laing Scientific. Prepare financial reports, review QBO entries, reconcile statements.',NULL,0,NULL,'high','pending','Quarterly Close','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339833','2026-05-14T01:27:29.339833');
INSERT INTO "tasks" VALUES(43,1,20,'Year-End Close (Dec) - Laing Scientific','Year-end bookkeeping close for Laing Scientific (YE: Dec). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339833','2026-05-14T01:27:29.339833');
INSERT INTO "tasks" VALUES(44,1,21,'Payroll - Align Plumbing','Monthly payroll processing for Align Plumbing. Calculate wages, deductions, prepare pay stubs, remit source deductions.',NULL,0,NULL,'high','pending','Payroll','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339849','2026-05-14T01:27:29.339849');
INSERT INTO "tasks" VALUES(45,1,21,'Year-End Close (Jul) - Align Plumbing','Year-end bookkeeping close for Align Plumbing (YE: Jul). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339849','2026-05-14T01:27:29.339849');
INSERT INTO "tasks" VALUES(46,1,21,'T4 Preparation - Align Plumbing','Annual T4 and T4 Summary preparation for Align Plumbing. Prepare employee T4s, file with CRA, distribute to employees.',NULL,0,NULL,'high','pending','T4/Tax','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339849','2026-05-14T01:27:29.339849');
INSERT INTO "tasks" VALUES(47,1,22,'Monthly Close - 2303851 Ontario Inc','Monthly bookkeeping close for 2303851 Ontario Inc. Reconcile accounts, review transactions, ensure all entries posted.',NULL,0,NULL,'high','pending','Monthly Close','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339871','2026-05-14T01:27:29.339871');
INSERT INTO "tasks" VALUES(48,1,22,'Year-End Close (Sept) - 2303851 Ontario Inc','Year-end bookkeeping close for 2303851 Ontario Inc (YE: Sept). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339871','2026-05-14T01:27:29.339871');
INSERT INTO "tasks" VALUES(49,1,23,'WSIB Filing (due Q4) - Clark Pools Owen Sound','WSIB quarterly filing (due Q4) for Clark Pools Owen Sound. Calculate premiums, prepare return, submit to WSIB. (due Q4)',NULL,0,NULL,'medium','pending','WSIB','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339891','2026-05-14T01:27:29.339891');
INSERT INTO "tasks" VALUES(50,1,24,'Monthly Close - Motion Invest Inc','Monthly bookkeeping close for Motion Invest Inc. Reconcile accounts, review transactions, ensure all entries posted.',NULL,0,NULL,'high','pending','Monthly Close','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339908','2026-05-14T01:27:29.339908');
INSERT INTO "tasks" VALUES(51,1,24,'Year-End Close (Sept) - Motion Invest Inc','Year-end bookkeeping close for Motion Invest Inc (YE: Sept). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339908','2026-05-14T01:27:29.339908');
INSERT INTO "tasks" VALUES(52,1,25,'Monthly Close - Fractal SaaS Inc','Monthly bookkeeping close for Fractal SaaS Inc. Reconcile accounts, review transactions, ensure all entries posted.',NULL,0,NULL,'high','pending','Monthly Close','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339927','2026-05-14T01:27:29.339927');
INSERT INTO "tasks" VALUES(53,1,25,'Year-End Close (Sept) - Fractal SaaS Inc','Year-end bookkeeping close for Fractal SaaS Inc (YE: Sept). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339927','2026-05-14T01:27:29.339927');
INSERT INTO "tasks" VALUES(54,1,26,'Monthly Close - Adbank Inc','Monthly bookkeeping close for Adbank Inc. Reconcile accounts, review transactions, ensure all entries posted.',NULL,0,NULL,'high','pending','Monthly Close','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339944','2026-05-14T01:27:29.339944');
INSERT INTO "tasks" VALUES(55,1,26,'Year-End Close (Sept) - Adbank Inc','Year-end bookkeeping close for Adbank Inc (YE: Sept). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.339944','2026-05-14T01:27:29.339944');
INSERT INTO "tasks" VALUES(56,1,27,'Year-End Close (Sept) - Listing Eagle','Year-end bookkeeping close for Listing Eagle (YE: Sept). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340032','2026-05-14T01:27:29.340032');
INSERT INTO "tasks" VALUES(57,1,28,'Monthly Close - Marketing Strategy Ventures','Monthly bookkeeping close for Marketing Strategy Ventures. Reconcile accounts, review transactions, ensure all entries posted.',NULL,0,NULL,'high','pending','Monthly Close','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340055','2026-05-14T01:27:29.340055');
INSERT INTO "tasks" VALUES(58,1,28,'Year-End Close (Sept) - Marketing Strategy Ventures','Year-end bookkeeping close for Marketing Strategy Ventures (YE: Sept). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340055','2026-05-14T01:27:29.340055');
INSERT INTO "tasks" VALUES(59,1,29,'Year-End Close (Sept) - Seahorse Health Inc','Year-end bookkeeping close for Seahorse Health Inc (YE: Sept). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Jon',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340073','2026-05-14T01:27:29.340073');
INSERT INTO "tasks" VALUES(60,1,30,'Payroll - Sher-E-Punjab','Bi-weekly payroll processing for Sher-E-Punjab. Calculate wages, deductions, prepare pay stubs, remit source deductions.',NULL,0,NULL,'high','pending','Payroll','Markie',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340089','2026-05-14T01:27:29.340089');
INSERT INTO "tasks" VALUES(61,1,30,'T4 Preparation - Sher-E-Punjab','Annual T4 and T4 Summary preparation for Sher-E-Punjab. Prepare employee T4s, file with CRA, distribute to employees.',NULL,0,NULL,'high','pending','T4/Tax','Markie',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340089','2026-05-14T01:27:29.340089');
INSERT INTO "tasks" VALUES(62,1,31,'Year-End Close (Dec) - Unimax Construction Group LLC','Year-end bookkeeping close for Unimax Construction Group LLC (YE: Dec). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340107','2026-05-14T01:27:29.340107');
INSERT INTO "tasks" VALUES(63,1,32,'Year-End Close (Jun) - M.M. Kapala','Year-end bookkeeping close for M.M. Kapala (YE: Jun). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Marriana',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340121','2026-05-14T01:27:29.340121');
INSERT INTO "tasks" VALUES(64,1,33,'Year-End Close (Nov) - Alderson','Year-end bookkeeping close for Alderson (YE: Nov). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','Rocco',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340136','2026-05-14T01:27:29.340136');
INSERT INTO "tasks" VALUES(65,1,41,'Year-End Close (Mar) - Brookebuilt Inc','Year-end bookkeeping close for Brookebuilt Inc (YE: Mar). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340214','2026-05-14T01:27:29.340214');
INSERT INTO "tasks" VALUES(66,1,42,'Payroll - Culbert''s Bakery Ltd','Bi-weekly payroll processing for Culbert''s Bakery Ltd. Calculate wages, deductions, prepare pay stubs, remit source deductions.',NULL,0,NULL,'high','pending','Payroll','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340229','2026-05-14T01:27:29.340229');
INSERT INTO "tasks" VALUES(67,1,42,'Year-End Close (Sept) - Culbert''s Bakery Ltd','Year-end bookkeeping close for Culbert''s Bakery Ltd (YE: Sept). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340229','2026-05-14T01:27:29.340229');
INSERT INTO "tasks" VALUES(68,1,42,'T4 Preparation - Culbert''s Bakery Ltd','Annual T4 and T4 Summary preparation for Culbert''s Bakery Ltd. Prepare employee T4s, file with CRA, distribute to employees.',NULL,0,NULL,'high','pending','T4/Tax','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340229','2026-05-14T01:27:29.340229');
INSERT INTO "tasks" VALUES(69,1,43,'Year-End Close (Dec) - Damiva Canada','Year-end bookkeeping close for Damiva Canada (YE: Dec). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340249','2026-05-14T01:27:29.340249');
INSERT INTO "tasks" VALUES(70,1,44,'Quarterly Close - Lemysta Systems','Quarterly bookkeeping close for Lemysta Systems. Prepare financial reports, review QBO entries, reconcile statements.',NULL,0,NULL,'high','pending','Quarterly Close','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340261','2026-05-14T01:27:29.340261');
INSERT INTO "tasks" VALUES(71,1,44,'Year-End Close (Sept) - Lemysta Systems','Year-end bookkeeping close for Lemysta Systems (YE: Sept). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340261','2026-05-14T01:27:29.340261');
INSERT INTO "tasks" VALUES(72,1,45,'Year-End Close (Dec) - MRM Software Inc','Year-end bookkeeping close for MRM Software Inc (YE: Dec). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340278','2026-05-14T01:27:29.340278');
INSERT INTO "tasks" VALUES(73,1,47,'Year-End Close (Dec) - Thames Valley Brick & Tile','Year-end bookkeeping close for Thames Valley Brick & Tile (YE: Dec). Reconcile all accounts, prepare working papers, tax prep.',NULL,0,NULL,'high','pending','Year-End','N/A',NULL,1,1,NULL,NULL,NULL,'2026-05-14T01:27:29.340291','2026-05-14T01:27:29.340291');
CREATE TABLE `time_entries` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`userId` integer NOT NULL,
	`taskId` integer,
	`date` integer NOT NULL,
	`description` text NOT NULL,
	`hours` real NOT NULL,
	`isBillable` integer DEFAULT true NOT NULL,
	`hourlyRate` real,
	`category` text DEFAULT 'bookkeeping' NOT NULL,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `timesheets` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`employeeId` integer NOT NULL,
	`payPeriodStart` integer NOT NULL,
	`payPeriodEnd` integer NOT NULL,
	`regularHours` real DEFAULT 0,
	`overtimeHours` real DEFAULT 0,
	`vacationHours` real DEFAULT 0,
	`sickHours` real DEFAULT 0,
	`statHolidayHours` real DEFAULT 0,
	`hourlyRate` real,
	`overtimeRate` real,
	`status` text DEFAULT 'draft' NOT NULL,
	`approvedBy` integer,
	`approvedAt` integer,
	`notes` text,
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `triage_findings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`agentName` text NOT NULL,
	`agentVersion` text,
	`clientId` integer,
	`findingType` text NOT NULL,
	`severity` text NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`suggestedAction` text,
	`sourceData` text,
	`confidence` real,
	`status` text DEFAULT 'new' NOT NULL,
	`reviewedBy` integer,
	`reviewedAt` integer,
	`reviewedNotes` text,
	`createdAt` integer
);
CREATE TABLE `user_settings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`userId` integer NOT NULL,
	`notifyTaskDue` integer DEFAULT true NOT NULL,
	`notifyTaskOverdue` integer DEFAULT true NOT NULL,
	`notifyInvoiceOverdue` integer DEFAULT true NOT NULL,
	`notifyNewEmail` integer DEFAULT false NOT NULL,
	`notifyCalendarEvent` integer DEFAULT true NOT NULL,
	`notifyClientActivity` integer DEFAULT false NOT NULL,
	`notifyAIAgent` integer DEFAULT true NOT NULL,
	`notifyQBO` integer DEFAULT true NOT NULL,
	`dashboardWidgets` text DEFAULT '["stats","tasks","emails","calendar","qbo"]',
	`defaultView` text DEFAULT 'dashboard',
	`theme` text DEFAULT 'system',
	`timezone` text DEFAULT 'UTC',
	`dateFormat` text DEFAULT 'MMM d, yyyy',
	`currency` text DEFAULT 'USD',
	`createdAt` integer,
	`updatedAt` integer
);
CREATE TABLE `users` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`unionId` text,
	`email` text NOT NULL,
	`name` text,
	`avatar` text,
	`role` text DEFAULT 'junior_bookkeeper' NOT NULL,
	`passwordHash` text,
	`authProvider` text DEFAULT 'local' NOT NULL,
	`isActive` integer DEFAULT true NOT NULL,
	`resetToken` text,
	`resetTokenExpires` integer,
	`createdAt` integer,
	`updatedAt` integer,
	`lastSignInAt` integer
);
INSERT INTO "users" VALUES(1,NULL,'markie@gofig.ca','Markie',NULL,'admin','$2a$12$vkebGJMne0cWF3.JhKH4xeBW78.FRI..11zHGMNDOjESb.Om2ty4i','local',1,NULL,NULL,'2026-05-13T10:44:56.075Z','2026-05-13T10:44:56.075Z',1778690300);
CREATE TABLE `workflow_logs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`clientId` integer NOT NULL,
	`fromStatus` text,
	`toStatus` text NOT NULL,
	`action` text NOT NULL,
	`notes` text,
	`performedBy` integer,
	`createdAt` integer
);
CREATE UNIQUE INDEX `client_onboarding_token_unique` ON `client_onboarding` (`token`);
CREATE UNIQUE INDEX `client_playbooks_clientId_unique` ON `client_playbooks` (`clientId`);
CREATE UNIQUE INDEX `portal_settings_clientId_unique` ON `portal_settings` (`clientId`);
CREATE UNIQUE INDEX `portal_tokens_token_unique` ON `portal_tokens` (`token`);
CREATE UNIQUE INDEX `user_settings_userId_unique` ON `user_settings` (`userId`);
CREATE UNIQUE INDEX `users_unionId_unique` ON `users` (`unionId`);
CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('users',1);
INSERT INTO "sqlite_sequence" VALUES('clients',50);
INSERT INTO "sqlite_sequence" VALUES('tasks',73);
COMMIT;
