-- GFB Active Clients Import
-- Generated from GFB_Client_Master_Government_Data_R1.xlsx
-- 32 active clients

BEGIN TRANSACTION;

INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('ORIGINALITY.AI INC.', 'ORIGINALITY.AI INC.', 'support@originality.ai', NULL, '64 Hurontario St, Suite 200, Collingwood, ON L9Y 2L6', 'technology', 'active', 'originality.ai', 'markie+originalityaiinc@gofig.ca', 'An AI-powered platform that detects AI-generated content and plagiarism. Founded in 2022 in Collingwood, Ontario.', 'Jon Gillham', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('CLARK POOLS AND SPAS COLLINGWOOD INC.', 'Clark Pools Collingwood', 'office@clarkpoolscollingwood.com', '(705) 445-6165', '20 Balsam St, Collingwood, ON L9Y 4H7', 'other', 'active', 'clarkpoolscollingwood.com', 'markie+clarkpoolsandspascollingwoodinc@gofig.ca', 'Complete pool and spa service company serving South Georgian Bay for over 20 years.', 'Jon', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('CLARK POOLS AND SPAS OWEN SOUND INC.', 'Clark Pools Owen Sound', 'info@clarkpools.com', '(519) 372-9411', '718028 Hwy 6, Owen Sound, ON N4K 5N7', 'other', 'active', 'clarkpools.com', 'markie+clarkpoolsandspasowensoundinc@gofig.ca', 'Pool and spa experts serving Owen Sound and Grey Bruce County for over 40 years.', 'Jon', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('WEST YORK PAVING LTD.', 'West York Paving', NULL, '(416) 231-6394', '200 Rexdale Blvd, Etobicoke, ON M9W 1R2', 'construction', 'active', 'westyorkpaving.com', 'markie+westyorkpavingltd@gofig.ca', 'Large paving company serving Toronto and GTA. Operated by the Barone family. Weekly payroll.', 'Joe & Frank Barone', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('1000235299 ONTARIO LTD. (The Auld Spot Pub)', 'The Auld Spot Pub', NULL, '(416) 461-1114', '347 Danforth Ave, Toronto, ON M4K 1N7', 'restaurant', 'active', 'auldspotpub.ca', 'markie+1000235299ontarioltdtheauldspotpub@gofig.ca', 'Scottish-style pub on Toronto Danforth since 1975. Uses TouchBistro POS.', 'Nathan Hynes', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('1001196626 ONTARIO LTD. (Sher-E-Punjab)', 'Sher-E-Punjab', NULL, '(416) 465-2125', '351 Danforth Ave, Toronto, ON M4K 1N7', 'restaurant', 'active', 'sher-e-punjab.ca', 'markie+1001196626ontarioltdsherepunjab@gofig.ca', 'Indian fine dining restaurant on Toronto Danforth since 1975.', 'Jaspal', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('KING INDUSTRIES INC.', 'King Industries', NULL, '(877) 289-3625', '29 Nobel Rd, McDougall, ON P2A 2W9', 'manufacturing', 'active', 'kingindustries.com', 'markie+kingindustriesinc@gofig.ca', 'Specialty chemical additives manufacturer. Also operates Dock Kings division.', 'Brad', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('OVITA CONSTRUCTION LTD.', 'Ovita Construction', NULL, '(905) 851-7744', '6260 Highway 7, Unit 7, Vaughan, ON L4H 4G3', 'construction', 'active', 'ovitaconstruction.com', 'markie+ovitaconstructionltd@gofig.ca', 'Building restoration and general contracting. High-rise construction specialists.', 'Rocco', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('OVITA HOLDINGS INC.', 'Ovita Holdings', NULL, NULL, 'Vaughan, ON', 'holding_company', 'active', NULL, 'markie+ovitaholdingsinc@gofig.ca', 'Holding company for Ovita Construction. Related entity — interco transactions with Ovita Construction.', 'Rocco', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('UNIVERSAL CONSTRUCTION GROUP INC.', 'Universal Construction Group', 'Universalconstructionyeg1605@gmail.com', '(416) 722-9447', 'Woodbridge, ON L4H 1N6', 'construction', 'active', 'universalcontructionyeg.com', 'markie+universalconstructiongroupinc@gofig.ca', 'Residential and commercial construction across Ontario.', 'Andrew', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('ALIGN BY DESIGN HD INC.', 'Align By Design', 'hello@alignanddesign.ca', '(647) 200-3501', 'Toronto, ON', 'professional_services', 'active', 'alignanddesign.ca', 'markie+alignbydesignhdinc@gofig.ca', 'Professional organizing and interior styling service.', 'Amy', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('GOTOMARKET AGILITY INC.', 'GoToMarket Agility', NULL, NULL, 'Toronto, ON', 'professional_services', 'active', 'gotomarketsolutions.ca', 'markie+gotomarketagilityinc@gofig.ca', 'Strategic consulting firm. Go-to-market planning and fractional CCO services.', 'Brad', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('ADBANK INC.', 'Adbank', 'hello@adbank.network', NULL, 'Collingwood, ON L9Y 1A1', 'technology', 'active', 'adbank.network', 'markie+adbankinc@gofig.ca', 'Digital advertising technology. Uses PayPal. Monthly reporting.', 'Jon', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('MOTION INVEST INC.', 'Motion Invest', 'contact@motioninvest.com', NULL, '1 First Street, Collingwood, ON L9Y 1A1', 'technology', 'active', 'motioninvest.com', 'markie+motioninvestinc@gofig.ca', 'Marketplace for buying and selling websites and YouTube channels. Monthly reporting.', 'Jon', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('FRACTAL SAAS INC.', 'Fractal SaaS', 'andrew@passed.ai', NULL, '64 Hurontario St, Suite 200, Collingwood, ON L9Y 2L6', 'technology', 'active', 'fractal.ai', 'markie+fractalsaasinc@gofig.ca', 'SaaS technology company. Uses Stripe. Monthly reporting.', 'Jon', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('LISTINGEAGLE.COM INC.', 'ListingEagle', NULL, NULL, 'Ontario, Canada', 'technology', 'active', NULL, 'markie+listingeaglecominc@gofig.ca', 'Digital solutions technology company. Annual reporting.', 'Jon', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('MARKETING STRATEGY VENTURES INC.', 'Marketing Strategy Ventures', NULL, NULL, 'Ontario, Canada', 'professional_services', 'active', NULL, 'markie+marketingstrategyventuresinc@gofig.ca', 'Marketing consulting. Uses Stripe and PayPal. Monthly reporting.', 'Jon', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('SEAHORSE HEALTH INC.', 'Seahorse Health', NULL, NULL, 'Ontario, Canada', 'healthcare', 'active', NULL, 'markie+seahorsehealthinc@gofig.ca', 'Healthcare business based in Collingwood. Annual reporting.', 'Jon', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('M.M. KAPALA MEDICINE PROFESSIONAL CORPORATION', 'M.M. Kapala Medicine', NULL, NULL, 'Ontario, Canada', 'healthcare', 'active', NULL, 'markie+mmkapalamedicineprofessionalcorporation@gofig.ca', 'Medical professional corporation. Annual reporting.', 'Marriana', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('ALDERSON DEVELOPMENTS LTD.', 'Alderson Developments', NULL, '(905) 934-1372', 'St Catharines, ON', 'construction', 'active', 'aldersonconsulting.ca', 'markie+aldersondevelopmentsltd@gofig.ca', 'Real estate development company. Annual reporting.', 'Rocco', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('2303851 ONTARIO INC.', '2303851 Ontario', NULL, NULL, 'Ontario, Canada', 'holding_company', 'active', NULL, 'markie+2303851ontarioinc@gofig.ca', 'Holding company — PRIMARY PAYER for Jon Gillham group. Uses Stripe and PayPal. Interco transactions with all related Jon entities.', 'Jon', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('STUDIO LELLA INC.', 'Studio Lella', 'studiolellainc@gmail.com', '(905) 893-5550', '110 Nashville Rd, Unit 10, Kleinburg, ON L0J 1C0', 'personal_services', 'active', 'studiolella.ca', 'markie+studiolellainc@gofig.ca', 'Hair styling studio in Kleinburg. Quarterly reporting.', 'Anthony', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('DARK HORSE INTELLIGENCE INC.', 'Dark Horse Intelligence', NULL, '1-800-261-1832', 'Ontario, Canada', 'technology', 'active', 'darkhorsevisualization.com', 'markie+darkhorseintelligenceinc@gofig.ca', 'Data visualization and predictive analytics. DBA: Darkhorse Analytics. Monthly payroll.', 'Daniel Haight', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('12738988 CANADA INC.', '12738988 Canada', NULL, NULL, '30 Esther Lorrie Drive, Etobicoke, ON', 'other', 'active', NULL, 'markie+12738988canadainc@gofig.ca', 'Federal corporation. Private entity.', NULL, 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('UNIMAX LTÉE / UNIMAX LTD.', 'Unimax', 'reception@unimax-int.com', '(416) 818-5288', '235 Rue J-A Bombardier, Boucherville, QC J4B 8P1', 'import_export', 'active', 'unimax.ca', 'markie+unimaxlteunimaxltd@gofig.ca', 'International import/export. Tire distribution. Canada + Florida USA operations.', 'Andrew/Michael/Frederico', 'QC', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('1001411380 ONTARIO INC. (Columbus Cafe)', 'Columbus Cafe', 'info@columbuscafe.co', '(905) 956-9501', '220 Yonge St, Toronto, ON M5B 2H1', 'restaurant', 'active', 'columbuscafe.ca', 'markie+1001411380ontarioinccolumbuscafe@gofig.ca', 'European cafe chain. Multiple Ontario locations.', NULL, 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('ALIGN PLUMBING INC.', 'Align Plumbing', NULL, '(519) 595-8843', '6414 Road 140, Milverton, ON N0K 1M0', 'construction', 'active', 'alignplumbing.ca', 'markie+alignplumbinginc@gofig.ca', 'Professional plumbing services. Annual reporting.', 'Adam', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('Aim Construction Inc.', 'Aim Construction', NULL, '(519) 747-2255', 'Cambridge, ON', 'construction', 'active', 'aimbuilders.ca', 'markie+aimconstructioninc@gofig.ca', 'Residential and commercial construction. Annual reporting.', 'Dan', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('Selective Painting', 'Selective Painting', 'gianluca@selectivepainting.ca', '(647) 407-0972', '25 Bella Vista Ct, Woodbridge, ON L4L 7P5', 'construction', 'active', 'selectivepainting.ca', 'markie+selectivepainting@gofig.ca', 'GTA residential and commercial painters. Annual reporting.', 'Gianluca', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('Laing Scientific', 'Laing Scientific', NULL, NULL, '2405 Lake Shore Blvd W, Etobicoke, ON M8V 1C6', 'other', 'active', NULL, 'markie+laingscientific@gofig.ca', 'Scientific equipment supplier. Microscopes and balances. Quarterly reporting.', 'Dave', 'ON', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('Universal Drywall', 'Universal Drywall', NULL, '(403) 635-0887', 'Florida, USA', 'construction', 'active', 'universaldrywall.com', 'markie+universaldrywall@gofig.ca', 'Drywall and construction. USA entity (Florida).', 'Michael', 'FL', 1778866324, 1778866324);
INSERT OR IGNORE INTO clients (name, company, email, phone, address, industry, workflowStatus, website, figgyEmail, notes, contactName, province, createdAt, updatedAt) VALUES ('Fleming Advisory Inc.', 'Fleming Advisory', NULL, NULL, 'Ontario, Canada', 'technology', 'active', NULL, 'markie+flemingadvisoryincformerlykaavio@gofig.ca', 'Technology and advisory. Formerly Kaavio — renamed by owner John. Annual reporting.', 'John', 'ON', 1778866324, 1778866324);

INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'ORIGINALITY.AI INC.', '786440610', '1000380932', 1670198400, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'ORIGINALITY.AI INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'CLARK POOLS AND SPAS COLLINGWOOD INC.', '770298602', '1000001017', 1634601600, 'Ontario Business Corp', 'ON', 1, 'biweekly', 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'CLARK POOLS AND SPAS COLLINGWOOD INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'CLARK POOLS AND SPAS OWEN SOUND INC.', '715666566', '1001447196', 1765929600, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'CLARK POOLS AND SPAS OWEN SOUND INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'WEST YORK PAVING LTD.', '877933515', '1491517', 999561600, 'Ontario Business Corp', 'ON', 1, 'weekly', 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'WEST YORK PAVING LTD.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, '1000235299 ONTARIO LTD. (The Auld Spot Pub)', '718843600', '1000235299', 1655337600, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 1, 1778866324, 1778866324 FROM clients WHERE name = '1000235299 ONTARIO LTD. (The Auld Spot Pub)' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, '1001196626 ONTARIO LTD. (Sher-E-Punjab)', '706313020', '1001196626', 1743638400, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = '1001196626 ONTARIO LTD. (Sher-E-Punjab)' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'KING INDUSTRIES INC.', '858977705', '6206522', 1079049600, 'Federal Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'KING INDUSTRIES INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'OVITA CONSTRUCTION LTD.', '752504498', '2536157', 1473638400, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'OVITA CONSTRUCTION LTD.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'OVITA HOLDINGS INC.', '722717121', '2567485', 1489968000, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'OVITA HOLDINGS INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'UNIVERSAL CONSTRUCTION GROUP INC.', '741962930', '2747411', 1583798400, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'UNIVERSAL CONSTRUCTION GROUP INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'ALIGN BY DESIGN HD INC.', '707477733', '12404648', 1602115200, 'Federal Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'ALIGN BY DESIGN HD INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'GOTOMARKET AGILITY INC.', '817061252', '2240452', 1271203200, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'GOTOMARKET AGILITY INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'ADBANK INC.', '793523481', '2597757', 1505865600, 'Ontario Business Corp', 'ON', 0, NULL, 0, 1, 0, 1778866324, 1778866324 FROM clients WHERE name = 'ADBANK INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'MOTION INVEST INC.', '728898321', '2560628', 1486598400, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'MOTION INVEST INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'FRACTAL SAAS INC.', '739247070', '2750934', 1585872000, 'Ontario Business Corp', 'ON', 0, NULL, 1, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'FRACTAL SAAS INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'LISTINGEAGLE.COM INC.', '767302490', '2520953', 1464652800, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'LISTINGEAGLE.COM INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'MARKETING STRATEGY VENTURES INC.', '763289337', '2724538', 1572480000, 'Ontario Business Corp', 'ON', 0, NULL, 1, 1, 0, 1778866324, 1778866324 FROM clients WHERE name = 'MARKETING STRATEGY VENTURES INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'SEAHORSE HEALTH INC.', '728509522', '2561240', 1486944000, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'SEAHORSE HEALTH INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'M.M. KAPALA MEDICINE PROFESSIONAL CORPORATION', '827463951', '1758046', 1198022400, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'M.M. KAPALA MEDICINE PROFESSIONAL CORPORATION' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'ALDERSON DEVELOPMENTS LTD.', '774355168', '1001174780', 1741910400, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'ALDERSON DEVELOPMENTS LTD.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, '2303851 ONTARIO INC.', '847759909', '2303851', 1319760000, 'Ontario Business Corp', 'ON', 0, NULL, 1, 1, 0, 1778866324, 1778866324 FROM clients WHERE name = '2303851 ONTARIO INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'STUDIO LELLA INC.', '792026429', '1000816710', 1709164800, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'STUDIO LELLA INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'DARK HORSE INTELLIGENCE INC.', '750383671', '2739028', 1579824000, 'Ontario Business Corp', 'ON', 1, 'monthly', 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'DARK HORSE INTELLIGENCE INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, '12738988 CANADA INC.', '781088661', '12738988', 1613260800, 'Federal Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = '12738988 CANADA INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'UNIMAX LTÉE / UNIMAX LTD.', '105448658', '14799691', 1677628800, 'Federal Business Corp', 'QC', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'UNIMAX LTÉE / UNIMAX LTD.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, '1001411380 ONTARIO INC. (Columbus Cafe)', '758960231', '1001411380', 1762819200, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = '1001411380 ONTARIO INC. (Columbus Cafe)' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'ALIGN PLUMBING INC.', '789978301', '13154424', NULL, 'Ontario Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'ALIGN PLUMBING INC.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'Aim Construction Inc.', '807649798', NULL, NULL, NULL, 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'Aim Construction Inc.' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'Selective Painting', '784617565', NULL, NULL, NULL, 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'Selective Painting' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'Laing Scientific', '127437374', NULL, NULL, NULL, 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'Laing Scientific' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'Universal Drywall', NULL, NULL, NULL, NULL, 'FL', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'Universal Drywall' LIMIT 1;
INSERT OR IGNORE INTO client_onboarding (clientId, businessLegalName, businessNumber, corporationNumber, incorporationDate, businessType, province, hasPayroll, payrollFrequency, usesStripe, usesPaypal, usesSquare, createdAt, updatedAt) SELECT id, 'Fleming Advisory Inc.', '736845488', '10980170', 1536192000, 'Federal Business Corp', 'ON', 0, NULL, 0, 0, 0, 1778866324, 1778866324 FROM clients WHERE name = 'Fleming Advisory Inc.' LIMIT 1;

COMMIT;

-- Imported 32 active clients
