-- GFB Clients Seed v5 — matches actual schema exactly
BEGIN TRANSACTION;

DELETE FROM client_onboarding;
DELETE FROM clients;

INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'ORIGINALITY.AI INC.','support@originality.ai',NULL,'Originality.AI','64 Hurontario St, Collingwood, ON','active','active','AI content detection. Jon Gillham group.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'CLARK POOLS COLLINGWOOD','office@clarkpoolscollingwood.com','(705) 445-6165','Clark Pools Collingwood','20 Balsam St, Collingwood, ON','active','active','Pool and spa. Biweekly payroll. Jon Gillham group.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'CLARK POOLS OWEN SOUND','info@clarkpools.com','(519) 372-9411','Clark Pools Owen Sound','718028 Hwy 6, Owen Sound, ON','active','active','Pool and spa. Owen Sound. Jon Gillham group.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'WEST YORK PAVING LTD.','info@westyorkpaving.com','(416) 231-6394','West York Paving','200 Rexdale Blvd, Etobicoke, ON','active','active','WEEKLY payroll. Barone family. Not tech-savvy.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'THE AULD SPOT PUB','info@auldspotpub.ca','(416) 461-1114','The Auld Spot Pub','347 Danforth Ave, Toronto, ON','active','active','Scottish pub, Danforth since 1975. Uses Square POS. Nathan Hynes.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'SHER-E-PUNJAB','info@sher-e-punjab.ca','(416) 465-2125','Sher-E-Punjab','351 Danforth Ave, Toronto, ON','active','active','Indian fine dining, Danforth since 1975. Jaspal.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'KING INDUSTRIES INC.','info@kingindustries.com','(877) 289-3625','King Industries','29 Nobel Rd, McDougall, ON','active','active','Specialty chemical additives. Dock Kings division. Brad.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'OVITA CONSTRUCTION LTD.','info@ovitaconstruction.com','(905) 851-7744','Ovita Construction','6260 Highway 7, Vaughan, ON','active','active','Building restoration and high-rise. Rocco.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'OVITA HOLDINGS INC.','info@ovitaholdings.com',NULL,'Ovita Holdings','Vaughan, ON','active','active','Holding company. Interco with Ovita Construction. Rocco.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'UNIVERSAL CONSTRUCTION GROUP INC.','Universalconstructionyeg1605@gmail.com','(416) 722-9447','Universal Construction Group','Woodbridge, ON','active','active','Residential and commercial construction Ontario. Andrew.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'ALIGN BY DESIGN HD INC.','hello@alignanddesign.ca','(647) 200-3501','Align By Design','Toronto, ON','active','active','Professional organizing and interior styling. Amy.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'GOTOMARKET AGILITY INC.','info@gotomarketsolutions.ca',NULL,'GoToMarket Agility','Toronto, ON','active','active','Strategic consulting. Fractional CCO. Brad.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'ADBANK INC.','hello@adbank.network',NULL,'Adbank','Collingwood, ON','active','active','Digital advertising tech. Uses PayPal. Jon Gillham group.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'MOTION INVEST INC.','contact@motioninvest.com',NULL,'Motion Invest','Collingwood, ON','active','active','Website marketplace. Jon Gillham group. Markie processes seller payments.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'FRACTAL SAAS INC.','andrew@passed.ai',NULL,'Fractal SaaS','Collingwood, ON','active','active','SaaS technology. Uses Stripe. Jon Gillham group.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'LISTINGEAGLE.COM INC.','info@listingeagle.com',NULL,'ListingEagle','Ontario, Canada','active','active','Digital solutions. Jon Gillham group.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'MARKETING STRATEGY VENTURES INC.','info@marketingstrategyventures.com',NULL,'Marketing Strategy Ventures','Ontario, Canada','active','active','Marketing consulting. Stripe and PayPal. Jon Gillham group.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'SEAHORSE HEALTH INC.','info@seahorsehealth.com',NULL,'Seahorse Health','Ontario, Canada','active','active','Healthcare. Jon Gillham group.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'M.M. KAPALA MEDICINE PROF. CORP.','info@mmkapala.com',NULL,'M.M. Kapala Medicine','Ontario, Canada','active','active','Medical professional corporation. Marriana.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'ALDERSON DEVELOPMENTS LTD.','info@aldersonconsulting.ca','(905) 934-1372','Alderson Developments','St Catharines, ON','active','active','Real estate development. Rocco.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'2303851 ONTARIO INC.','info@2303851ontario.com',NULL,'2303851 Ontario','Ontario, Canada','active','active','PRIMARY PAYER for Jon Gillham group. Stripe and PayPal.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'STUDIO LELLA INC.','studiolellainc@gmail.com','(905) 893-5550','Studio Lella','110 Nashville Rd, Kleinburg, ON','active','active','Hair styling studio, Kleinburg. Anthony.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'DARK HORSE INTELLIGENCE INC.','info@darkhorsevisualization.com','1-800-261-1832','Dark Horse Intelligence','Ontario, Canada','active','active','Data visualization and analytics. Monthly payroll. Daniel Haight.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'12738988 CANADA INC.','info@12738988canada.com',NULL,'12738988 Canada','30 Esther Lorrie Dr, Etobicoke, ON','active','active','Federal corporation.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'COLUMBUS CAFE','info@columbuscafe.co','(905) 956-9501','Columbus Cafe','220 Yonge St, Toronto, ON','active','active','European cafe chain. Multiple Ontario locations.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'ALIGN PLUMBING INC.','info@alignplumbing.ca','(519) 595-8843','Align Plumbing','6414 Road 140, Milverton, ON','active','active','Professional plumbing. Adam.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'AIM CONSTRUCTION INC.','info@aimbuilders.ca','(519) 747-2255','Aim Construction','Cambridge, ON','active','active','Residential and commercial construction. Dan.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'SELECTIVE PAINTING','gianluca@selectivepainting.ca','(647) 407-0972','Selective Painting','25 Bella Vista Ct, Woodbridge, ON','active','active','GTA painters. Gianluca.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'LAING SCIENTIFIC','info@laingscientific.com',NULL,'Laing Scientific','2405 Lake Shore Blvd W, Etobicoke, ON','active','active','Scientific equipment. Dave.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'FLEMING ADVISORY INC.','info@flemingadvisory.com',NULL,'Fleming Advisory','Ontario, Canada','active','active','Technology and advisory. Formerly Kaavio. John.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'UNIVERSAL DRYWALL','info@universaldrywall.com','(403) 635-0887','Universal Drywall','Florida, USA','active','active','Drywall and construction. Florida USA. Michael.',1778866324,1778866324);
INSERT INTO clients (userId,name,email,phone,company,address,status,workflowStatus,notes,createdAt,updatedAt) VALUES ((SELECT id FROM users LIMIT 1),'UNIMAX LTD.','reception@unimax-int.com','(416) 818-5288','Unimax','Florida, USA','active','active','Import/export. Tire distribution. Florida USA.',1778866324,1778866324);

COMMIT;
-- 32 clients using exact schema columns only
