-- GFB Active Clients Import — Clean v4 (no industry column)
BEGIN TRANSACTION;
DELETE FROM client_onboarding;
DELETE FROM clients;

INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('ORIGINALITY.AI INC.','Originality.AI','support@originality.ai',NULL,'64 Hurontario St, Collingwood, ON','active','originality.ai','markie+originalityaiinc@gofig.ca','AI content detection. Jon Gillham group.','Jon Gillham','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('CLARK POOLS AND SPAS COLLINGWOOD INC.','Clark Pools Collingwood','office@clarkpoolscollingwood.com','(705) 445-6165','20 Balsam St, Collingwood, ON','active','clarkpoolscollingwood.com','markie+clarkpoolscollingwood@gofig.ca','Pool and spa. Biweekly payroll. Jon Gillham group.','Jon Gillham','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('CLARK POOLS AND SPAS OWEN SOUND INC.','Clark Pools Owen Sound','info@clarkpools.com','(519) 372-9411','718028 Hwy 6, Owen Sound, ON','active','clarkpools.com','markie+clarkpoolsowensound@gofig.ca','Pool and spa. Owen Sound. Jon Gillham group.','Jon Gillham','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('WEST YORK PAVING LTD.','West York Paving',NULL,'(416) 231-6394','200 Rexdale Blvd, Etobicoke, ON','active','westyorkpaving.com','markie+westyorkpaving@gofig.ca','WEEKLY payroll. Barone family. Not tech-savvy.','Joe & Frank Barone','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('1000235299 ONTARIO LTD.','The Auld Spot Pub',NULL,'(416) 461-1114','347 Danforth Ave, Toronto, ON','active','auldspotpub.ca','markie+auldspotpub@gofig.ca','Scottish pub, Danforth since 1975. Uses Square POS.','Nathan Hynes','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('1001196626 ONTARIO LTD.','Sher-E-Punjab',NULL,'(416) 465-2125','351 Danforth Ave, Toronto, ON','active','sher-e-punjab.ca','markie+sherepunjab@gofig.ca','Indian fine dining, Danforth since 1975.','Jaspal','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('KING INDUSTRIES INC.','King Industries',NULL,'(877) 289-3625','29 Nobel Rd, McDougall, ON','active','kingindustries.com','markie+kingindustries@gofig.ca','Specialty chemical additives. Dock Kings division.','Brad','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('OVITA CONSTRUCTION LTD.','Ovita Construction',NULL,'(905) 851-7744','6260 Highway 7, Vaughan, ON','active','ovitaconstruction.com','markie+ovitaconstruction@gofig.ca','Building restoration and high-rise construction.','Rocco','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('OVITA HOLDINGS INC.','Ovita Holdings',NULL,NULL,'Vaughan, ON','active',NULL,'markie+ovitaholdings@gofig.ca','Holding company. Interco with Ovita Construction.','Rocco','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('UNIVERSAL CONSTRUCTION GROUP INC.','Universal Construction Group','Universalconstructionyeg1605@gmail.com','(416) 722-9447','Woodbridge, ON','active','universalconstructionyeg.com','markie+universalconstruction@gofig.ca','Residential and commercial construction Ontario.','Andrew','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('ALIGN BY DESIGN HD INC.','Align By Design','hello@alignanddesign.ca','(647) 200-3501','Toronto, ON','active','alignanddesign.ca','markie+alignbydesign@gofig.ca','Professional organizing and interior styling.','Amy','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('GOTOMARKET AGILITY INC.','GoToMarket Agility',NULL,NULL,'Toronto, ON','active','gotomarketsolutions.ca','markie+gotomarketagility@gofig.ca','Strategic consulting. Fractional CCO services.','Brad','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('ADBANK INC.','Adbank','hello@adbank.network',NULL,'Collingwood, ON','active','adbank.network','markie+adbank@gofig.ca','Digital advertising tech. Uses PayPal. Jon Gillham group.','Jon Gillham','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('MOTION INVEST INC.','Motion Invest','contact@motioninvest.com',NULL,'Collingwood, ON','active','motioninvest.com','markie+motioninvest@gofig.ca','Website marketplace. Jon Gillham group. Markie processes seller payments.','Jon Gillham','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('FRACTAL SAAS INC.','Fractal SaaS','andrew@passed.ai',NULL,'Collingwood, ON','active','fractal.ai','markie+fractalsaas@gofig.ca','SaaS technology. Uses Stripe. Jon Gillham group.','Jon Gillham','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('LISTINGEAGLE.COM INC.','ListingEagle',NULL,NULL,'Ontario, Canada','active',NULL,'markie+listingeagle@gofig.ca','Digital solutions. Jon Gillham group.','Jon Gillham','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('MARKETING STRATEGY VENTURES INC.','Marketing Strategy Ventures',NULL,NULL,'Ontario, Canada','active',NULL,'markie+msv@gofig.ca','Marketing consulting. Stripe and PayPal. Jon Gillham group.','Jon Gillham','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('SEAHORSE HEALTH INC.','Seahorse Health',NULL,NULL,'Ontario, Canada','active',NULL,'markie+seahorsehealth@gofig.ca','Healthcare. Jon Gillham group.','Jon Gillham','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('M.M. KAPALA MEDICINE PROFESSIONAL CORPORATION','M.M. Kapala Medicine',NULL,NULL,'Ontario, Canada','active',NULL,'markie+mmkapala@gofig.ca','Medical professional corporation.','Marriana','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('ALDERSON DEVELOPMENTS LTD.','Alderson Developments',NULL,'(905) 934-1372','St Catharines, ON','active','aldersonconsulting.ca','markie+aldersondevelopments@gofig.ca','Real estate development.','Rocco','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('2303851 ONTARIO INC.','2303851 Ontario',NULL,NULL,'Ontario, Canada','active',NULL,'markie+2303851ontario@gofig.ca','PRIMARY PAYER for Jon Gillham group. Stripe and PayPal.','Jon Gillham','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('STUDIO LELLA INC.','Studio Lella','studiolellainc@gmail.com','(905) 893-5550','110 Nashville Rd, Kleinburg, ON','active','studiolella.ca','markie+studiolella@gofig.ca','Hair styling studio, Kleinburg.','Anthony','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('DARK HORSE INTELLIGENCE INC.','Dark Horse Intelligence',NULL,'1-800-261-1832','Ontario, Canada','active','darkhorsevisualization.com','markie+darkhorse@gofig.ca','Data visualization and analytics. Monthly payroll.','Daniel Haight','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('12738988 CANADA INC.','12738988 Canada',NULL,NULL,'30 Esther Lorrie Dr, Etobicoke, ON','active',NULL,'markie+12738988canada@gofig.ca','Federal corporation.','','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('1001411380 ONTARIO INC.','Columbus Cafe','info@columbuscafe.co','(905) 956-9501','220 Yonge St, Toronto, ON','active','columbuscafe.ca','markie+columbuscafe@gofig.ca','European cafe chain. Multiple Ontario locations.','','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('ALIGN PLUMBING INC.','Align Plumbing',NULL,'(519) 595-8843','6414 Road 140, Milverton, ON','active','alignplumbing.ca','markie+alignplumbing@gofig.ca','Professional plumbing services.','Adam','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('AIM CONSTRUCTION INC.','Aim Construction',NULL,'(519) 747-2255','Cambridge, ON','active','aimbuilders.ca','markie+aimconstruction@gofig.ca','Residential and commercial construction.','Dan','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('SELECTIVE PAINTING','Selective Painting','gianluca@selectivepainting.ca','(647) 407-0972','25 Bella Vista Ct, Woodbridge, ON','active','selectivepainting.ca','markie+selectivepainting@gofig.ca','GTA painters.','Gianluca','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('LAING SCIENTIFIC','Laing Scientific',NULL,NULL,'2405 Lake Shore Blvd W, Etobicoke, ON','active',NULL,'markie+laingscientific@gofig.ca','Scientific equipment.','Dave','ON','ca_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('FLEMING ADVISORY INC.','Fleming Advisory',NULL,NULL,'Ontario, Canada','active',NULL,'markie+flemingadvisory@gofig.ca','Technology and advisory. Formerly Kaavio.','John','ON','ca_clients',1778866324,1778866324);

-- ========== GO FIG BOOKZ US ==========
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('UNIVERSAL DRYWALL','Universal Drywall',NULL,'(403) 635-0887','Florida, USA','active','universaldrywall.com','markie+universaldrywall@gofig.ca','Drywall and construction. Florida USA.','Michael','FL','us_clients',1778866324,1778866324);
INSERT INTO clients (name,company,email,phone,address,workflowStatus,website,figgyEmail,notes,contactName,province,qboAccountType,createdAt,updatedAt) VALUES ('UNIMAX LTD.','Unimax','reception@unimax-int.com','(416) 818-5288','Florida, USA','active','unimax.ca','markie+unimax@gofig.ca','Import/export. Tire distribution. Florida USA.','Andrew/Michael/Frederico','FL','us_clients',1778866324,1778866324);

COMMIT;
-- 30 CA + 2 US = 32 clients
