/**
 * GOOGLE SHEETS DATABASE LAYER
 * Replaces SQLite with Google Sheets as the primary data store.
 * Each table = one sheet tab. Each row = one record.
 */

import { eq, and, or, like, desc, sql } from "drizzle-orm";

// Sheet IDs and config
let SPREADSHEET_ID = "";
let ACCESS_TOKEN = "";

export function configureSheetsDb(spreadsheetId: string, accessToken: string) {
  SPREADSHEET_ID = spreadsheetId;
  ACCESS_TOKEN = accessToken;
}

export function getSpreadsheetId() {
  return SPREADSHEET_ID;
}

// All table names and their column headers
export const SHEET_SCHEMA: Record<string, string[]> = {
  users: ["id","unionId","name","email","role","avatar","createdAt"],
  clients: ["id","userId","name","email","phone","company","address","taxId","status","leadSource","assignedTo","monthlyFee","hourlyRate","billingType","notes","googleDriveFolderId","qboCustomerId","qboConnectionId","qboAccountType","referredBy","emergencyContactName","emergencyContactPhone","emergencyContactRelationship","lastContactedAt","createdAt","updatedAt"],
  tasks: ["id","userId","clientId","title","description","completed","status","priority","category","dueDate","assignedTo","createdAt","updatedAt"],
  timeEntries: ["id","clientId","userId","taskId","date","description","hours","isBillable","hourlyRate","category","createdAt","updatedAt"],
  emails: ["id","userId","connectedAccountId","clientId","threadId","fromAddress","toAddress","subject","body","direction","status","provider","sentAt"],
  calendar_events: ["id","userId","title","description","start","end","allDay","source","clientId"],
  portal_tokens: ["id","clientId","token","email","isActive","expiresAt","lastUsedAt"],
  portal_settings: ["id","clientId","showFinancialOverview","showTasks","showDocuments","showInvoices","showTaxDeadlines","welcomeMessage","isEnabled"],
  missing_items: ["id","clientId","title","description","category","status","dueDate","emailSentAt","emailSentCount"],
  portal_files: ["id","clientId","userId","name","description","provider","category","webViewLink","isVisible","createdAt"],
  signature_documents: ["id","clientId","userId","title","description","content","documentType","status","signedBy","signatureData","signedAt","portalToken","expiresAt"],
  engagement_letters: ["id","clientId","userId","title","content","monthlyFee","startDate","endDate","status"],
  client_playbooks: ["id","clientId","userId","autoGenerated","sections","createdAt","updatedAt"],
  satisfaction_scores: ["id","clientId","userId","score","notes","createdAt"],
  monthly_close_checklist: ["id","clientId","userId","year","month","completionPercent","notes","completedAt"],
  client_vault: ["id","clientId","userId","category","itemName","valueEncrypted","notes"],
  client_onboarding: ["id","clientId","legalName","operatingName","businessStructure","industry","craBusinessNumber","hstNumber","qstNumber","craPayrollAccount","eftCode","wsibAccountNumber","bankName","fiscalYearEnd","hstGstFrequency","payrollFrequency","employeeCount","subcontractorCount","serviceTier","monthlyFee","createdAt"],
  triage_findings: ["id","agentName","clientId","findingType","severity","title","description","status","createdAt"],
  employees: ["id","clientId","name","sin","dob","hireDate","payType","payRate","payrollFrequency","benefitsHealth","benefitsDental","benefitsRRSP","rrspMatchPercent","createdAt"],
  timesheets: ["id","employeeId","payPeriodStart","payPeriodEnd","regularHours","overtimeHours","vacationHours","sickHours","statHours","submittedAt"],
  invoices: ["id","userId","clientId","invoiceNumber","amount","status","dueDate","paidAt","createdAt"],
  qbo_connections: ["id","userId","realmId","companyName","environment","accountType","isActive","lastSyncedAt"],
  notifications: ["id","userId","type","title","message","severity","read","linkTo","createdAt"],
  connected_accounts: ["id","userId","provider","accountEmail","accountLabel","isActive"],
};

// Google Sheets API helpers
async function sheetsApi(path: string, method = "GET", body?: any) {
  const url = `https://sheets.googleapis.com/v4/spreadsheets/${SPREADSHEET_ID}${path}`;
  const res = await fetch(url, {
    method,
    headers: {
      Authorization: `Bearer ${ACCESS_TOKEN}`,
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Sheets API error: ${res.status} ${err}`);
  }
  return res.json();
}

// Get all data from a sheet
export async function getAll(sheetName: string): Promise<Record<string, any>[]> {
  try {
    const result = await sheetsApi(`/values/${sheetName}!A:Z`);
    const rows = result.values || [];
    if (rows.length < 2) return [];
    const headers = rows[0];
    return rows.slice(1).map((row: string[]) => {
      const obj: Record<string, any> = {};
      headers.forEach((h: string, i: number) => {
        obj[h] = row[i] || "";
      });
      // Auto-convert types
      if (obj.id) obj.id = parseInt(obj.id) || 0;
      if (obj.userId) obj.userId = parseInt(obj.userId) || 0;
      if (obj.clientId) obj.clientId = parseInt(obj.clientId) || 0;
      if (obj.hours) obj.hours = parseFloat(obj.hours) || 0;
      if (obj.score) obj.score = parseInt(obj.score) || 0;
      if (obj.monthlyFee) obj.monthlyFee = parseFloat(obj.monthlyFee) || 0;
      if (obj.completed === "true" || obj.completed === "1") obj.completed = true;
      if (obj.completed === "false" || obj.completed === "0") obj.completed = false;
      if (obj.isActive === "true" || obj.isActive === "1") obj.isActive = true;
      if (obj.isActive === "false" || obj.isActive === "0") obj.isActive = false;
      if (obj.isVisible === "true" || obj.isVisible === "1") obj.isVisible = true;
      if (obj.isVisible === "false" || obj.isVisible === "0") obj.isVisible = false;
      return obj;
    });
  } catch {
    return [];
  }
}

// Insert a row
export async function insert(sheetName: string, data: Record<string, any>): Promise<Record<string, any>> {
  const headers = SHEET_SCHEMA[sheetName];
  if (!headers) throw new Error(`Unknown sheet: ${sheetName}`);

  // Get next ID
  const all = await getAll(sheetName);
  const nextId = all.length > 0 ? Math.max(...all.map((r) => r.id || 0)) + 1 : 1;
  data.id = nextId;

  // Set timestamps
  if (!data.createdAt) data.createdAt = new Date().toISOString();
  if (!data.updatedAt) data.updatedAt = new Date().toISOString();

  const row = headers.map((h) => {
    const v = data[h];
    if (v === undefined || v === null) return "";
    if (typeof v === "boolean") return v ? "1" : "0";
    return String(v);
  });

  await sheetsApi(`/values/${sheetName}!A:Z:append?valueInputOption=RAW`, "POST", {
    values: [row],
  });

  return data;
}

// Update a row by ID
export async function update(sheetName: string, id: number, data: Record<string, any>): Promise<void> {
  const all = await getAll(sheetName);
  const index = all.findIndex((r) => r.id === id);
  if (index === -1) throw new Error(`Row ${id} not found in ${sheetName}`);

  // Row index in sheet (0 = headers, so +2)
  const rowIndex = index + 2;
  const headers = SHEET_SCHEMA[sheetName];
  const existing = all[index];
  const merged = { ...existing, ...data, updatedAt: new Date().toISOString() };

  const row = headers.map((h) => {
    const v = merged[h];
    if (v === undefined || v === null) return "";
    if (typeof v === "boolean") return v ? "1" : "0";
    return String(v);
  });

  // Clear then rewrite
  const colEnd = String.fromCharCode(65 + headers.length - 1); // A, B, C... -> Z
  await sheetsApi(`/values/${sheetName}!A${rowIndex}:${colEnd}${rowIndex}?valueInputOption=RAW`, "PUT", {
    values: [row],
  });
}

// Delete a row by ID (mark as deleted)
export async function remove(sheetName: string, id: number): Promise<void> {
  await update(sheetName, id, { status: "deleted", deletedAt: new Date().toISOString() });
}

// Query with filters (simple AND)
export async function query(sheetName: string, filters: Record<string, any>): Promise<Record<string, any>[]> {
  const all = await getAll(sheetName);
  return all.filter((row) => {
    for (const [key, value] of Object.entries(filters)) {
      if (row[key] !== value && String(row[key]) !== String(value)) return false;
    }
    return true;
  });
}

// Create the master spreadsheet with all tabs
export async function createMasterSpreadsheet(accessToken: string, title = "Go Fig Bookz CRM Database"): Promise<string> {
  const res = await fetch("https://sheets.googleapis.com/v4/spreadsheets", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      properties: { title },
      sheets: Object.keys(SHEET_SCHEMA).map((name) => ({
        properties: { title: name },
      })),
    }),
  });
  const data = await res.json();
  const spreadsheetId = data.spreadsheetId;

  // Write headers to each sheet
  for (const [sheetName, headers] of Object.entries(SHEET_SCHEMA)) {
    await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}/values/${sheetName}!A1?valueInputOption=RAW`, {
      method: "PUT",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        values: [headers],
      }),
    });
  }

  return spreadsheetId;
}

// Initialize from connected Google account
export async function initFromConnectedAccount(db: any) {
  // Get the first active Google connected account
  const accounts = await db.select().from(db.$schema.connected_accounts)
    .where(and(eq(db.$schema.connected_accounts.provider, "google"), eq(db.$schema.connected_accounts.isActive, true)));

  if (!accounts[0]) return null;

  // Get fresh access token (this would use the stored refresh token)
  // For now, return the account info
  return accounts[0];
}
